import { useState } from 'react';
import type { TimelineItem } from '../../../types';
import { resolveIntervalPauseId, type RenderCellExtras } from './sheetModel';

/** Cellules éditables de la feuille de route : distance d'une pause, durée de pause. */

export function TimelineSheetDistanceCell({
  item,
  displayValue,
  extras,
}: {
  item: TimelineItem;
  displayValue: string;
  extras: RenderCellExtras;
}) {
  const { onMovePause, maxDistanceKm, t } = extras;
  const isPause = item.kind === 'pause';
  const canEdit = isPause && Boolean(onMovePause);

  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState('');

  const handleStartEdit = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!canEdit) return;
    setIsEditing(true);
    setDraft(item.distanceKm != null ? String(item.distanceKm) : '');
  };

  const handleCommit = () => {
    if (!isEditing) return;
    const clean = draft.trim().replace(',', '.');
    const parsed = parseFloat(clean);
    if (!Number.isNaN(parsed) && parsed >= 0) {
      let finalKm = parsed;
      if (maxDistanceKm != null && maxDistanceKm > 0) {
        finalKm = Math.min(finalKm, maxDistanceKm);
      }
      finalKm = Number(finalKm.toFixed(3));
      if (finalKm !== item.distanceKm) {
        onMovePause?.(item.id, finalKm);
      }
    }
    setIsEditing(false);
  };

  if (isEditing) {
    return (
      <input
        type="text"
        className="rvi-tl-td__distance-input"
        value={draft}
        autoFocus
        onChange={(e) => setDraft(e.target.value)}
        onBlur={handleCommit}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            handleCommit();
          } else if (e.key === 'Escape') {
            e.preventDefault();
            setIsEditing(false);
          }
        }}
        onClick={(e) => e.stopPropagation()}
        aria-label={t('Modifier la distance en kilomètres')}
      />
    );
  }

  if (canEdit) {
    return (
      <span
        className="rvi-tl-td__value rvi-tl-td__distance--editable"
        onClick={handleStartEdit}
        title={t('Modifier la distance (km)')}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            handleStartEdit(e as unknown as React.MouseEvent);
          }
        }}
      >
        {displayValue}
      </span>
    );
  }

  return <span className="rvi-tl-td__value">{displayValue}</span>;
}

export function TimelineSheetDurationCell({
  item,
  primaryLabel,
  extras,
}: {
  item: TimelineItem;
  primaryLabel: string;
  extras: RenderCellExtras;
}) {
  const { onChangePauseDuration, onChangeIntervalPauseDuration, t } = extras;
  const isAutoIntervalPause = item.autoGenerated === 'intervalPause';
  const canEdit = Boolean(
    isAutoIntervalPause ? onChangeIntervalPauseDuration : onChangePauseDuration,
  );

  const [isEditing, setIsEditing] = useState(false);
  const [draft, setDraft] = useState('');

  const handleStartEdit = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (!canEdit) return;
    setIsEditing(true);
    setDraft(item.durationMin != null ? String(item.durationMin) : '15');
  };

  const handleCommit = () => {
    if (!isEditing) return;
    const clean = draft.trim().replace(/\D/g, '');
    const parsed = parseInt(clean, 10);
    if (!Number.isNaN(parsed) && parsed > 0) {
      if (isAutoIntervalPause) {
        const intervalId = resolveIntervalPauseId(item.id);
        if (intervalId) {
          onChangeIntervalPauseDuration?.(intervalId, parsed);
        }
      } else {
        onChangePauseDuration?.(item.id, parsed);
      }
    }
    setIsEditing(false);
  };

  if (isEditing) {
    return (
      <input
        type="text"
        className="rvi-tl-td__duration-input"
        value={draft}
        autoFocus
        onChange={(e) => setDraft(e.target.value)}
        onBlur={handleCommit}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            e.preventDefault();
            handleCommit();
          } else if (e.key === 'Escape') {
            e.preventDefault();
            setIsEditing(false);
          }
        }}
        onClick={(e) => e.stopPropagation()}
        aria-label={t('Modifier la durée de la pause')}
      />
    );
  }

  return (
    <span
      className={`rvi-tl-td__name${canEdit ? ' rvi-tl-td__name--editable' : ''}`}
      title={canEdit ? t('Modifier la durée de la pause') : primaryLabel}
      onClick={canEdit ? handleStartEdit : undefined}
      role={canEdit ? 'button' : undefined}
      tabIndex={canEdit ? 0 : undefined}
      onKeyDown={
        canEdit
          ? (e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                handleStartEdit(e as unknown as React.MouseEvent);
              }
            }
          : undefined
      }
    >
      {primaryLabel}
    </span>
  );
}
