import type { TimelineItem } from '../../../types';
import { KindBadge, kindLabel } from '../KindBadge';
import { PlaceSearchInput } from '../components';
import type { TimelineColumnDef } from '../TimelineColumns';
import { TimelineSheetDistanceCell, TimelineSheetDurationCell } from './EditableSheetCells';
import type { PreparedRow, RenderCellExtras } from './sheetModel';

/** Contenu d'une cellule de la grille selon sa colonne (badge, type, nom / lieu, distance, valeur). */

function resolveSheetKindLabel(item: TimelineItem, t: (key: string) => string): string {
  if (item.kind === 'end') return t('Fin');
  return kindLabel(item.kind, item.poiCategory);
}

export function renderCell(
  col: TimelineColumnDef,
  row: PreparedRow,
  cellIndex: number,
  extras: RenderCellExtras,
) {
  const { item } = row;
  const cell = row.cells[cellIndex]!;

  if (col.id === 'typePicto') {
    return <KindBadge kind={item.kind} poiCategory={item.poiCategory} favorite={item.favorite} pauseDurationMin={item.durationMin} />;
  }
  if (col.id === 'typeText') {
    const label = resolveSheetKindLabel(item, extras.t);
    return (
      <span className="rvi-tl-td__type-text" title={label}>
        {label}
      </span>
    );
  }
  if (col.id === 'name') {
    return renderNameCell(item, extras);
  }
  if (col.id === 'distance') {
    return <TimelineSheetDistanceCell item={item} displayValue={cell.display} extras={extras} />;
  }
  return <span className="rvi-tl-td__value">{cell.display}</span>;
}

function renderNameCell(item: TimelineItem, extras: RenderCellExtras) {
  const { t } = extras;
  const searchPlaceholder = t('Rechercher un lieu');
  const isPlaceholder =
    item.label === searchPlaceholder || item.label === 'Rechercher un lieu' || item.label.trim() === '';
  const isLocationRow =
    item.kind === 'start' || item.kind === 'end' || item.kind === 'waypoint';
  const useSearchInput = !!extras.onSelectPlace && isLocationRow;

  const isAutoIntervalPause = item.autoGenerated === 'intervalPause';
  const isPause = item.kind === 'pause';
  const primaryLabel =
    isPause && item.durationMin
      ? (isAutoIntervalPause ? `${t(item.label)} · ${item.durationMin}min` : `${item.durationMin}min`)
      : item.label;

  if (useSearchInput) {
    return (
      <PlaceSearchInput
        value={isPlaceholder ? '' : item.label}
        onPick={(s) =>
          extras.onSelectPlace?.(item.id, {
            name: s.name,
            fullName: s.fullName,
            lat: s.lat,
            lon: s.lon,
          })
        }
        placeholder={searchPlaceholder}
      />
    );
  }

  if (isPause) {
    return (
      <TimelineSheetDurationCell
        item={item}
        primaryLabel={primaryLabel}
        extras={extras}
      />
    );
  }

  return (
    <span
      className={`rvi-tl-td__name${isPlaceholder ? ' rvi-tl-td__name--placeholder' : ''}`}
      title={primaryLabel}
    >
      {primaryLabel}
    </span>
  );
}
