import { memo } from 'react';
import type { TimelineItem } from '../../../types';
import { IconNiceManYellow, IconStar, IconTrash } from '../../../components/icons';
import type { TimelineColumnDef } from '../TimelineColumns';
import { renderCell } from './renderSheetCell';
import { CELL_ALIGN_CLASS, type PreparedRow, type RenderCellExtras } from './sheetModel';

interface TimelineSheetGridRowProps {
  row: PreparedRow;
  rowIndex: number;
  selected: boolean;
  visibleColumns: TimelineColumnDef[];
  cellExtras: RenderCellExtras;
  onSelectRow?: (id: string, item: TimelineItem) => void;
  onToggleSelect?: (id: string, selected: boolean) => void;
  onToggleVisibility?: (id: string, visible: boolean) => void;
  onToggleFavorite?: (id: string, favorite: boolean) => void;
  onRemove?: (id: string) => void;
}

/** Ligne de la grille, mémoïsée : un défilement ne rend que les lignes entrantes. */
export const TimelineSheetGridRow = memo(function TimelineSheetGridRow({
  row,
  rowIndex,
  selected,
  visibleColumns,
  cellExtras,
  onSelectRow,
  onToggleSelect,
  onToggleVisibility,
  onToggleFavorite,
  onRemove,
}: TimelineSheetGridRowProps) {
  const { item } = row;
  const { t } = cellExtras;
  const visible = item.visible !== false;
  const isAutoIntervalPause = item.autoGenerated === 'intervalPause';
  return (
    <div
      role="row"
      className={`rvi-tl-tr${selected ? ' is-selected' : ''}`}
      data-kind={item.kind}
      data-timeline-id={item.id}
      data-vrow={item.id}
      style={{ animationDelay: `${Math.min(rowIndex * 18, 240)}ms` }}
      onClick={(e) => {
        const target = e.target as HTMLElement | null;
        if (target?.closest('button, input, select, label, .rvi-tl-td__check, .rvi-tl-td--actions')) {
          return;
        }
        onSelectRow?.(item.id, item);
      }}
    >
      <div className="rvi-tl-td rvi-tl-td--sticky-left rvi-tl-td--check" role="cell">
        <label className="rvi-tl-td__check">
          <input
            type="checkbox"
            checked={selected}
            onChange={(e) => onToggleSelect?.(item.id, e.target.checked)}
            aria-label={t('Sélectionner')}
          />
          <span className="rvi-tl-td__check-box" aria-hidden />
        </label>
      </div>

      {visibleColumns.map((col, colIndex) => (
        <div
          key={col.id}
          role="cell"
          className={`rvi-tl-td rvi-tl-td--${col.id} ${CELL_ALIGN_CLASS[col.align]}`}
        >
          {renderCell(col, row, colIndex, cellExtras)}
        </div>
      ))}

      <div className="rvi-tl-td rvi-tl-td--filler" aria-hidden />

      <div className="rvi-tl-td rvi-tl-td--sticky-right rvi-tl-td--actions" role="cell">
        <button
          type="button"
          className={`rvi-tl-tr__action${visible ? ' is-on' : ''}`}
          onClick={() => {
            if (isAutoIntervalPause) return;
            onToggleVisibility?.(item.id, !visible);
          }}
          aria-label={visible ? t('Masquer') : t('Afficher')}
          aria-pressed={visible}
          disabled={isAutoIntervalPause}
        >
          <IconNiceManYellow size={15} style={!visible ? { opacity: 0.35, filter: 'grayscale(1)' } : undefined} />
        </button>
        <button
          type="button"
          className="rvi-tl-tr__action rvi-tl-tr__action--danger"
          onClick={() => {
            if (isAutoIntervalPause) return;
            onRemove?.(item.id);
          }}
          aria-label={t('Supprimer')}
          disabled={isAutoIntervalPause}
        >
          <IconTrash size={15} />
        </button>
        <button
          type="button"
          className={`rvi-tl-tr__action rvi-tl-tr__action--star${item.favorite ? ' is-on is-fav' : ''}`}
          onClick={() => {
            if (isAutoIntervalPause) return;
            onToggleFavorite?.(item.id, !item.favorite);
          }}
          aria-label={t('Favori')}
          aria-pressed={!!item.favorite}
          disabled={isAutoIntervalPause}
        >
          <IconStar size={12} />
        </button>
      </div>
    </div>
  );
});
