import type { PoiAutoSortReason, PoiFavoriteSource } from '../../poi/types';
import type { PoiCategory } from './poi';

// Feuille de route (lignes, filtres, vues tableau / frise).

export interface TimelineFilterState {
  etape: boolean;
  waypoint: boolean;
  poi: boolean;
  pause: boolean;
  favorite: boolean;
  categories?: Set<string>;
}

export type TimelineItemKind =
  | 'start'
  | 'end'
  | 'waypoint'
  | 'water'
  | 'supermarket'
  | 'poi'
  | 'pause';

export type TimelineAddItemKind =
  | 'step'
  | 'waypoint'
  | 'poi'
  | 'pause'
  | 'start'
  | 'end';

export interface TimelineAddItemOptions {
  distanceKm?: number;
}

export interface TimelineItem {
  id: string;
  kind: TimelineItemKind;
  label: string;
  /**
   * `label` saisi par l'utilisateur dans la colonne « Nom » (horaires, nom
   * raccourci…) : gardé quand la recherche POI régénère les lignes, et repris
   * tel quel par les exports GPS après le code de catégorie.
   */
  labelEdited?: boolean;
  /** Distance depuis le départ en km. */
  distanceKm: number | null;
  /** Pour une pause : durée en minutes. */
  durationMin?: number;
  favorite?: boolean;
  visible?: boolean;
  /** Lignes synthétiques dérivées d'une autre source et non persistées directement dans la timeline. */
  autoGenerated?: 'intervalPause';
  /** Coordonnées géographiques une fois que l'utilisateur a résolu un lieu par la recherche. */
  lat?: number;
  lon?: number;
  /** Indique que l'étape a été posée directement sur le tracé existant et sert d'ancre sans recalcul initial. */
  onRoute?: boolean;
  /**
   * Pour les éléments `kind: 'poi'` injectés par la recherche dans le couloir —
   * la catégorie de POI du panneau, utilisée par `KindBadge` pour afficher la
   * bonne épingle en goutte et par `kindLabel` pour afficher le nom de la
   * sous-catégorie (Eau, Boulangerie…).
   */
  poiCategory?: PoiCategory;
  /** Id OSM stable de l'élément source, quand la ligne a été injectée par la recherche de POI. */
  osmId?: number;
  /**
   * Favori posé à la main (absent = manuel). `'auto'` : favori posé par
   * l'ancien tri automatique, effacé au prochain tri (voir `clearPoiAutoSortFavorites`).
   */
  favoriteSource?: PoiFavoriteSource;
  /** Règle de l'ancien tri automatique qui avait retenu ce favori. */
  autoReason?: PoiAutoSortReason;
}

export type TimelineView = 'sheet' | 'timeline';

/**
 * Configuration de la vue « Timeline » (rail kilométrique vertical).
 *
 * Le rail est une pile de lignes de hauteur fixe, chacune représentant
 * `kmPerRow` kilomètres. Les éléments sont positionnés en absolu par-dessus le
 * rail, à un décalage en pixels de `(distanceKm / kmPerRow) * rowHeightPx`.
 */
export interface TimelineRailConfig {
  /** Kilomètres représentés par chaque ligne. 10 par défaut. */
  kmPerRow: number;
  /** Hauteur en pixels d'une ligne. 32 par défaut. */
  rowHeightPx: number;
}

export const DEFAULT_TIMELINE_RAIL: TimelineRailConfig = {
  kmPerRow: 10,
  rowHeightPx: 32,
};
