import type { PoiAutoSortReason, PoiFavoriteSource } from '../../poi/types';
import type { PoiCategory } from './poi';

// Feuille de route (lignes, filtres, vues tableau / frise).

export interface TimelineFilterState {
  etape: boolean;
  waypoint: boolean;
  poi: boolean;
  pause: boolean;
  favorite: boolean;
  categories?: Set<string>;
}

export type TimelineItemKind =
  | 'start'
  | 'end'
  | 'waypoint'
  | 'water'
  | 'supermarket'
  | 'poi'
  | 'pause';

export type TimelineAddItemKind =
  | 'step'
  | 'waypoint'
  | 'poi'
  | 'pause'
  | 'start'
  | 'end';

export interface TimelineAddItemOptions {
  distanceKm?: number;
}

export interface TimelineItem {
  id: string;
  kind: TimelineItemKind;
  label: string;
  /** Distance from start in km. */
  distanceKm: number | null;
  /** For pause: duration in minutes. */
  durationMin?: number;
  favorite?: boolean;
  visible?: boolean;
  /** Synthetic rows derived from another source and not directly persisted in timeline. */
  autoGenerated?: 'intervalPause';
  /** Geo coordinates once the user has resolved a place via search. */
  lat?: number;
  lon?: number;
  /** Indicates the waypoint was placed directly on the existing route track and acts as an anchor without initial recalculation. */
  onRoute?: boolean;
  /**
   * For `kind: 'poi'` items injected by the corridor search — the panel
   * POI category, used by `KindBadge` to render the right teardrop pin
   * and by `kindLabel` to display the sub-category name (Eau, Boulangerie…).
   */
  poiCategory?: PoiCategory;
  /** Stable OSM id of the source feature, when the row was injected by POI search. */
  osmId?: number;
  /**
   * Favori posé à la main (absent = manuel). `'auto'` : favori posé par
   * l'ancien tri automatique, effacé au prochain tri (voir `clearPoiAutoSortFavorites`).
   */
  favoriteSource?: PoiFavoriteSource;
  /** Règle de l'ancien tri automatique qui avait retenu ce favori. */
  autoReason?: PoiAutoSortReason;
}

export type TimelineView = 'sheet' | 'timeline';

/**
 * Configuration for the "Timeline" (vertical km-rail) view.
 *
 * The rail is a stack of fixed-height rows, each representing `kmPerRow`
 * kilometres. Items are absolutely positioned on top of the rail at a
 * pixel offset of `(distanceKm / kmPerRow) * rowHeightPx`.
 */
export interface TimelineRailConfig {
  /** Kilometres represented by each row. Defaults to 10. */
  kmPerRow: number;
  /** Pixel height of a single row. Defaults to 32. */
  rowHeightPx: number;
}

export const DEFAULT_TIMELINE_RAIL: TimelineRailConfig = {
  kmPerRow: 10,
  rowHeightPx: 32,
};
