export const PROVIDED_POI_SVG = {
  water: '/svgv2/poi/eau.svg',
  bakery: '/svgv2/poi/boulangerie.svg',
  cafe: '/svgv2/poi/cafe.svg',
  fastFood: '/svgv2/poi/fastfood.svg',
  shop: '/svgv2/poi/magasin.svg',
  supermarket: '/svgv2/poi/supermarche.svg',
  bikeShop: '/svgv2/poi/magasindevelo.svg',
  restaurant: '/svgv2/poi/restaurant.svg',
  fuel: '/svgv2/poi/stationservice.svg',
  toilet: '/svgv2/poi/toilette.svg',
  bar: '/svgv2/poi/bar.svg',
  hotelBadge: '/svgv2/poi/hotel.svg',
  refugeBadge: '/svgv2/poi/refuge.svg',
  hotelGlyph: '/svgv2/poi/icon_hotel.svg',
  refugeGlyph: '/svgv2/poi/icon_refuge.svg',
  hotelPin: '/svgv2/poi/hotel.svg',
  refugePin: '/svgv2/poi/refuge.svg',
} as const;