export const PANEL_WIDTH_KEY = 'rvc-panel-width';
export const LEFT_PANEL_WIDTH_MIN = 360;
export const PANEL_WIDTH_MIN_FALLBACK = LEFT_PANEL_WIDTH_MIN;
export const PANEL_WIDTH_MAX = 560;
export const PANEL_WIDTH_DEFAULT = 300;
export const PANEL_PADDING = 12;
export const PANEL_COLLAPSE_DRAG_THRESHOLD = 64;
export const RIGHT_PANEL_COLLAPSED_RAIL_WIDTH = 40;
export const COLLAPSED_DRAWER_CLEARANCE = 46;
export const CENTER_PANEL_HEIGHT_KEY = 'rvc-center-panel-height';

export const LEFT_PANEL_WIDTH_KEY = 'rvi-panel-width';
export const LEFT_PANEL_WIDTH_MAX = 520;
export const LEFT_PANEL_WIDTH_DEFAULT = 360;

export const CENTER_PANEL_MIN_WIDTH = 420;
export const CENTER_PANEL_MIN_HEIGHT = 350;
export const CENTER_PANEL_MIN_HEIGHT_RATIO = 0.38;
export const CENTER_PANEL_DEFAULT_HEIGHT_RATIO = 0.44;
export const CENTER_PANEL_MAX_HEIGHT_RATIO = 0.58;
export const MAP_VIEWPORT_CONTROLS_TOTAL_HEIGHT = 360;
export const CENTER_PANEL_MIN_MAP_STAGE = PANEL_PADDING + MAP_VIEWPORT_CONTROLS_TOTAL_HEIGHT + PANEL_PADDING; // 384px
export const CENTER_TOOLBAR_HEIGHT = 48;
export const CENTER_PANEL_STACK_GAP = PANEL_PADDING;
export const CENTER_PANEL_RESIZE_HIT_AREA = 18;

export const IMMERSIVE_TRANSITION_MS = 320;
export const IMMERSIVE_EASING = 'cubic-bezier(0.22, 1, 0.36, 1)';

export const APP_SCALE_MIN = 0.45;
export const APP_SCALE_DESIGN_WIDTH = 1920;
export const APP_SCALE_DESIGN_HEIGHT = 1080;
