// Scénarios du banc de qualité neige.

import type { WorldSpec } from './world';

const NW = 300;

export const SCENARIOS: WorldSpec[] = [
  {
    name: 'hiver-nw',
    seed: 11,
    analysisIso: '2026-02-15T06:00:00Z',
    temp1500C: -3.5,
    tempTrendCPerDay: 0.02,
    storms: [
      { daysAgo: 52, hours: 36, windFromDeg: NW, windMs: 16, precipMmH: 2.2, tempOffsetC: -3 },
      { daysAgo: 38, hours: 30, windFromDeg: NW + 20, windMs: 14, precipMmH: 2.0, tempOffsetC: -2 },
      { daysAgo: 21, hours: 44, windFromDeg: NW, windMs: 18, precipMmH: 2.6, tempOffsetC: -4 },
      { daysAgo: 6, hours: 24, windFromDeg: NW - 15, windMs: 15, precipMmH: 1.8, tempOffsetC: -3 },
    ],
    foehnDaysAgo: [30],
    precipAnomaly: 0.12,
    forest: false,
    truthWindPerDeg: 0.03,
    noiseSigma: 0.12,
    aromePrecipBias: 0,
    aromeTempBiasC: 0,
    orographyNoiseM: 30,
    stationCount: 0,
    braNoiseCm: null,
    weatherNoiseC: 0.8,
  },
  {
    name: 'hiver-arome-biaise+stations',
    seed: 23,
    analysisIso: '2026-02-20T06:00:00Z',
    temp1500C: -2.5,
    tempTrendCPerDay: 0.02,
    storms: [
      { daysAgo: 60, hours: 40, windFromDeg: NW, windMs: 15, precipMmH: 2.4, tempOffsetC: -3 },
      { daysAgo: 33, hours: 36, windFromDeg: NW + 10, windMs: 17, precipMmH: 2.2, tempOffsetC: -3 },
      { daysAgo: 12, hours: 30, windFromDeg: NW, windMs: 16, precipMmH: 2.0, tempOffsetC: -2 },
    ],
    foehnDaysAgo: [24],
    precipAnomaly: 0.15,
    forest: true,
    truthWindPerDeg: 0.03,
    noiseSigma: 0.12,
    aromePrecipBias: -0.3,
    aromeTempBiasC: 1.2,
    orographyNoiseM: 40,
    stationCount: 7,
    braNoiseCm: 8,
    weatherNoiseC: 0.8,
  },
  {
    name: 'printemps-fonte',
    seed: 37,
    analysisIso: '2026-04-12T06:00:00Z',
    temp1500C: 2.0,
    tempTrendCPerDay: 0.12,
    storms: [
      { daysAgo: 70, hours: 40, windFromDeg: NW, windMs: 15, precipMmH: 2.6, tempOffsetC: -4 },
      { daysAgo: 50, hours: 36, windFromDeg: NW, windMs: 16, precipMmH: 2.4, tempOffsetC: -3 },
      { daysAgo: 35, hours: 30, windFromDeg: NW + 15, windMs: 14, precipMmH: 2.2, tempOffsetC: -3 },
    ],
    foehnDaysAgo: [20, 8],
    precipAnomaly: 0.12,
    forest: true,
    truthWindPerDeg: 0.025,
    noiseSigma: 0.12,
    aromePrecipBias: 0.1,
    aromeTempBiasC: -0.5,
    orographyNoiseM: 30,
    stationCount: 5,
    braNoiseCm: 10,
    weatherNoiseC: 1.0,
  },
  {
    name: 'debut-saison-vent',
    seed: 41,
    analysisIso: '2026-12-10T06:00:00Z',
    temp1500C: -4,
    tempTrendCPerDay: 0.05,
    storms: [
      { daysAgo: 9, hours: 30, windFromDeg: NW + 30, windMs: 19, precipMmH: 1.6, tempOffsetC: -3 },
      { daysAgo: 3, hours: 18, windFromDeg: NW, windMs: 20, precipMmH: 1.2, tempOffsetC: -2 },
    ],
    foehnDaysAgo: [],
    precipAnomaly: 0.1,
    forest: false,
    truthWindPerDeg: 0.04,
    noiseSigma: 0.15,
    aromePrecipBias: 0.15,
    aromeTempBiasC: 0,
    orographyNoiseM: 30,
    stationCount: 3,
    braNoiseCm: null,
    weatherNoiseC: 0.8,
  },
];
