// AUTO-GENERATED by scripts/prebuild-api-i18n.mjs — do not edit manually
export const APP_TRANSLATION_PAIRS: ReadonlyArray<{ fr: string; en: string }> = [
  {
    "fr": "Loading...",
    "en": "Loading..."
  },
  {
    "fr": "Redirecting...",
    "en": "Redirecting..."
  },
  {
    "fr": "Loading dashboard...",
    "en": "Loading dashboard..."
  },
  {
    "fr": "Réglages globaux",
    "en": "Global settings"
  },
  {
    "fr": "Langue",
    "en": "Language"
  },
  {
    "fr": "Unité de mesure",
    "en": "Unit system"
  },
  {
    "fr": "Paramètre de carte",
    "en": "Map preset"
  },
  {
    "fr": "Préférence d’affichage",
    "en": "Display preference"
  },
  {
    "fr": "Réglage",
    "en": "Setting"
  },
  {
    "fr": "Activer le réglage",
    "en": "Enable setting"
  },
  {
    "fr": "Mètre",
    "en": "Meters"
  },
  {
    "fr": "Pieds",
    "en": "Feet"
  },
  {
    "fr": "Jour (nuit couché de soleil)",
    "en": "Day (sunset night)"
  },
  {
    "fr": "Nuit",
    "en": "Night"
  },
  {
    "fr": "System preference",
    "en": "System preference"
  },
  {
    "fr": "Light mode",
    "en": "Light mode"
  },
  {
    "fr": "Dark mode",
    "en": "Dark mode"
  },
  {
    "fr": "Construit avec et pour la communauté",
    "en": "Built with and for the community"
  },
  {
    "fr": "Notre questionnaire de feedback",
    "en": "Our feedback questionnaire"
  },
  {
    "fr": "Coordonnees",
    "en": "Contact details"
  },
  {
    "fr": "First name *",
    "en": "First name *"
  },
  {
    "fr": "Last name *",
    "en": "Last name *"
  },
  {
    "fr": "Email address *",
    "en": "Email address *"
  },
  {
    "fr": "Annuler",
    "en": "Cancel"
  },
  {
    "fr": "Enregistrement...",
    "en": "Saving..."
  },
  {
    "fr": "Enregistrer",
    "en": "Save"
  },
  {
    "fr": "Pratique",
    "en": "Practice"
  },
  {
    "fr": "Pays",
    "en": "Country"
  },
  {
    "fr": "Sport",
    "en": "Sport"
  },
  {
    "fr": "Level",
    "en": "Level"
  },
  {
    "fr": "Moyenne annuelle",
    "en": "Yearly average"
  },
  {
    "fr": "Ajouter un sport",
    "en": "Add a sport"
  },
  {
    "fr": "Velo de route",
    "en": "Road cycling"
  },
  {
    "fr": "Gravel",
    "en": "Gravel"
  },
  {
    "fr": "VTT",
    "en": "MTB"
  },
  {
    "fr": "Trail",
    "en": "Trail running"
  },
  {
    "fr": "Randonnee",
    "en": "Hiking"
  },
  {
    "fr": "Debutant",
    "en": "Beginner"
  },
  {
    "fr": "Intermediaire",
    "en": "Intermediate"
  },
  {
    "fr": "Avance",
    "en": "Advanced"
  },
  {
    "fr": "Expert",
    "en": "Expert"
  },
  {
    "fr": "Mot de passe",
    "en": "Password"
  },
  {
    "fr": "Current password *",
    "en": "Current password *"
  },
  {
    "fr": "Current password",
    "en": "Current password"
  },
  {
    "fr": "Mise a jour...",
    "en": "Updating..."
  },
  {
    "fr": "Changer le mot de passe",
    "en": "Change password"
  },
  {
    "fr": "Coordonnees enregistrees.",
    "en": "Contact details saved."
  },
  {
    "fr": "Impossible d’enregistrer le compte.",
    "en": "Unable to save the account."
  },
  {
    "fr": "Impossible d’enregistrer les informations de pratique.",
    "en": "Unable to save practice details."
  },
  {
    "fr": "Mot de passe mis a jour.",
    "en": "Password updated."
  },
  {
    "fr": "Impossible de mettre a jour le mot de passe.",
    "en": "Unable to update the password."
  },
  {
    "fr": "Chargement du compte...",
    "en": "Loading account..."
  },
  {
    "fr": "Aucune information de compte disponible.",
    "en": "No account information available."
  },
  {
    "fr": "Compte",
    "en": "Account"
  },
  {
    "fr": "Adresse indisponible",
    "en": "Address unavailable"
  },
  {
    "fr": "billing@votre-domaine.com",
    "en": "billing@your-domain.com"
  },
  {
    "fr": "Carte Bancaire",
    "en": "Bank card"
  },
  {
    "fr": "Numéro de carte",
    "en": "Card number"
  },
  {
    "fr": "Amazon Pay",
    "en": "Amazon Pay"
  },
  {
    "fr": "Numéro de carte *",
    "en": "Card number *"
  },
  {
    "fr": "CVV *",
    "en": "CVV *"
  },
  {
    "fr": "Name on card *",
    "en": "Name on card *"
  },
  {
    "fr": "Expiry *",
    "en": "Expiry *"
  },
  {
    "fr": "Country *",
    "en": "Country *"
  },
  {
    "fr": "Aucun abonnement Stripe à synchroniser après confirmation.",
    "en": "No Stripe subscription to sync after confirmation."
  },
  {
    "fr": "Saisissez le nom du titulaire de la carte.",
    "en": "Enter the cardholder name."
  },
  {
    "fr": "Le champ de carte Stripe est introuvable.",
    "en": "The Stripe card field could not be found."
  },
  {
    "fr": "Stripe n’a pas renvoyé de SetupIntent exploitable.",
    "en": "Stripe did not return a usable SetupIntent."
  },
  {
    "fr": "La confirmation Stripe a échoué.",
    "en": "Stripe confirmation failed."
  },
  {
    "fr": "Card details",
    "en": "Card details"
  },
  {
    "fr": "CVV",
    "en": "CVV"
  },
  {
    "fr": "Name on card",
    "en": "Name on card"
  },
  {
    "fr": "Expiry",
    "en": "Expiry"
  },
  {
    "fr": "Country",
    "en": "Country"
  },
  {
    "fr": "Configuration Stripe incomplète",
    "en": "Incomplete Stripe configuration"
  },
  {
    "fr": "Ajoutez VITE_STRIPE_PUBLISHABLE_KEY côté app pour activer la page de paiement intégrée.",
    "en": "Add VITE_STRIPE_PUBLISHABLE_KEY on the app side to enable the embedded payment page."
  },
  {
    "fr": "Stripe indisponible",
    "en": "Stripe unavailable"
  },
  {
    "fr": "Confirmation…",
    "en": "Confirming..."
  },
  {
    "fr": "En fournissant vos informations de carte bancaire, vous autorisez RedView à débiter votre carte pour les paiements futurs conformément à ses conditions. Les données de votre carte sont traitées par Stripe, RedView n’enregistre jamais le PAN complet.",
    "en": "By providing your card information, you authorize RedView to charge your card for future payments in accordance with its terms. Your card data is processed by Stripe; RedView never stores the full PAN."
  },
  {
    "fr": "Ouvrir RedView Web",
    "en": "Open RedView Web"
  },
  {
    "fr": "Premium",
    "en": "Premium"
  },
  {
    "fr": "Actif",
    "en": "Active"
  },
  {
    "fr": "Essai",
    "en": "Trial"
  },
  {
    "fr": "Statut indisponible",
    "en": "Status unavailable"
  },
  {
    "fr": "Projets",
    "en": "Projects"
  },
  {
    "fr": "Abonnement",
    "en": "Subscription"
  },
  {
    "fr": "Réglages",
    "en": "Settings"
  },
  {
    "fr": "Navigation principale du menu projet",
    "en": "Main project menu navigation"
  },
  {
    "fr": "Utilisateur",
    "en": "User"
  },
  {
    "fr": "Déconnexion...",
    "en": "Signing out..."
  },
  {
    "fr": "Se déconnecter",
    "en": "Sign out"
  },
  {
    "fr": "Sélecteur de projet principal",
    "en": "Main project selector"
  },
  {
    "fr": "Enregistrement de votre e-mail de facturation…",
    "en": "Saving your billing email..."
  },
  {
    "fr": "E-mail de facturation enregistré.",
    "en": "Billing email saved."
  },
  {
    "fr": "Impossible d’enregistrer l’e-mail de facturation.",
    "en": "Unable to save the billing email."
  },
  {
    "fr": "Impossible de charger les informations d’abonnement.",
    "en": "Unable to load subscription details."
  },
  {
    "fr": "Gestion de l’abonnement",
    "en": "Subscription management"
  },
  {
    "fr": "Découvrir les offres payantes",
    "en": "Explore paid plans"
  },
  {
    "fr": "Reprendre",
    "en": "Resume"
  },
  {
    "fr": "Interrompre",
    "en": "Pause"
  },
  {
    "fr": "Basculer sur cette offre",
    "en": "Switch to this plan"
  },
  {
    "fr": "Choisir cette offre",
    "en": "Choose this plan"
  },
  {
    "fr": "Choisir une offre payante",
    "en": "Choose a paid plan"
  },
  {
    "fr": "Remplacer mon moyen de paiement",
    "en": "Replace my payment method"
  },
  {
    "fr": "Ajouter un moyen de paiement",
    "en": "Add a payment method"
  },
  {
    "fr": "Passer à une offre payante",
    "en": "Upgrade to a paid plan"
  },
  {
    "fr": "Remplacer le moyen de paiement",
    "en": "Replace payment method"
  },
  {
    "fr": "Aucun moyen de paiement par défaut",
    "en": "No default payment method"
  },
  {
    "fr": "Plan Demo sans paiement",
    "en": "Demo plan without payment"
  },
  {
    "fr": "Ajoutez ou remplacez votre carte directement dans RedView App.",
    "en": "Add or replace your card directly in RedView App."
  },
  {
    "fr": "Confirmer le changement de plan",
    "en": "Confirm plan change"
  },
  {
    "fr": "Finaliser votre abonnement",
    "en": "Complete your subscription"
  },
  {
    "fr": "Choisissez votre mode de paiement pour vous abonner.",
    "en": "Choose your payment method to subscribe."
  },
  {
    "fr": "Confirmer le changement",
    "en": "Confirm change"
  },
  {
    "fr": "Activer l’abonnement",
    "en": "Activate subscription"
  },
  {
    "fr": "Mettre à jour votre moyen de paiement",
    "en": "Update your payment method"
  },
  {
    "fr": "Enregistrer cette carte",
    "en": "Save this card"
  },
  {
    "fr": "Impossible d’ouvrir le formulaire de carte.",
    "en": "Unable to open the card form."
  },
  {
    "fr": "Impossible de lancer cette action de facturation.",
    "en": "Unable to start this billing action."
  },
  {
    "fr": "Impossible de mettre à jour le renouvellement automatique.",
    "en": "Unable to update auto-renewal."
  },
  {
    "fr": "Impossible de se déconnecter.",
    "en": "Unable to sign out."
  },
  {
    "fr": "Impossible de charger les informations du compte.",
    "en": "Unable to load account details."
  },
  {
    "fr": "Affichage des projets",
    "en": "Project display"
  },
  {
    "fr": "Grille",
    "en": "Grid"
  },
  {
    "fr": "Liste",
    "en": "List"
  },
  {
    "fr": "Rechercher…",
    "en": "Search..."
  },
  {
    "fr": "Rechercher un projet",
    "en": "Search for a project"
  },
  {
    "fr": "Créer un dossier",
    "en": "Create folder"
  },
  {
    "fr": "Création…",
    "en": "Creating..."
  },
  {
    "fr": "Créer un projet",
    "en": "Create project"
  },
  {
    "fr": "Créer un élément",
    "en": "Create item"
  },
  {
    "fr": "Créer un projet ici",
    "en": "Create project here"
  },
  {
    "fr": "Créer un dossier ici",
    "en": "Create folder here"
  },
  {
    "fr": "Contenu du dossier courant",
    "en": "Current folder contents"
  },
  {
    "fr": "Liste des projets",
    "en": "Project list"
  },
  {
    "fr": "Chargement…",
    "en": "Loading..."
  },
  {
    "fr": "Aucun dossier ou projet ne correspond à votre recherche.",
    "en": "No folder or project matches your search."
  },
  {
    "fr": "Ce dossier est vide. Créez un sous-dossier ou un projet pour commencer.",
    "en": "This folder is empty. Create a subfolder or project to get started."
  },
  {
    "fr": "Vous n’avez pas encore de projet. Créez un dossier ou un projet pour commencer.",
    "en": "You do not have any project yet. Create a folder or project to get started."
  },
  {
    "fr": "Racine / Projets",
    "en": "Root / Projects"
  },
  {
    "fr": "Nouveau nom du projet",
    "en": "New project name"
  },
  {
    "fr": "Nouveau nom du dossier",
    "en": "New folder name"
  },
  {
    "fr": "Actions du projet",
    "en": "Project actions"
  },
  {
    "fr": "Actions du dossier",
    "en": "Folder actions"
  },
  {
    "fr": "Double-cliquer pour renommer",
    "en": "Double-click to rename"
  },
  {
    "fr": "Aperçu de projet",
    "en": "Project preview"
  },
  {
    "fr": "Chemin du dossier courant",
    "en": "Current folder path"
  },
  {
    "fr": "Renommer le dossier",
    "en": "Rename folder"
  },
  {
    "fr": "Renommer le projet",
    "en": "Rename project"
  },
  {
    "fr": "Déplacer vers…",
    "en": "Move to..."
  },
  {
    "fr": "Destinations disponibles",
    "en": "Available destinations"
  },
  {
    "fr": "Dupliquer le projet",
    "en": "Duplicate project"
  },
  {
    "fr": "Supprimer le dossier",
    "en": "Delete folder"
  },
  {
    "fr": "Supprimer le projet",
    "en": "Delete project"
  },
  {
    "fr": "Projet",
    "en": "Project"
  },
  {
    "fr": "Dossier",
    "en": "Folder"
  },
  {
    "fr": "Découvrir les offres",
    "en": "Explore plans"
  },
  {
    "fr": "Abonnements",
    "en": "Subscriptions"
  },
  {
    "fr": "Découvrez nos offres d’abonnement.",
    "en": "Explore our subscription offers."
  },
  {
    "fr": "Informations de paiement",
    "en": "Payment information"
  },
  {
    "fr": "E-mail de contact",
    "en": "Contact email"
  },
  {
    "fr": "Envoyer sur mon e-mail de compte",
    "en": "Send to my account email"
  },
  {
    "fr": "Envoyer sur un e-mail alternatif",
    "en": "Send to an alternative email"
  },
  {
    "fr": "Vous êtes sur une démo réduite de RedView. Pour activer l’interface, choisissez votre abonnement:",
    "en": "You are on a reduced RedView demo. To unlock the full interface, choose your subscription:"
  },
  {
    "fr": "Démo",
    "en": "Demo"
  },
  {
    "fr": "Gratuit",
    "en": "Free"
  },
  {
    "fr": "Abonnement Explorer",
    "en": "Explorer plan"
  },
  {
    "fr": "Abonnement Pro",
    "en": "Pro plan"
  },
  {
    "fr": "Engagement de 6 mois",
    "en": "6-month commitment"
  },
  {
    "fr": "Sans engagement",
    "en": "No commitment"
  },
  {
    "fr": "Stockage Cloud",
    "en": "Cloud storage"
  },
  {
    "fr": "Gestionnaire de projet",
    "en": "Project manager"
  },
  {
    "fr": "Cartographie 3D HD",
    "en": "HD 3D mapping"
  },
  {
    "fr": "Cartographie 3D haute fidélité",
    "en": "High-fidelity 3D mapping"
  },
  {
    "fr": "Analyse LIDAR 20cm",
    "en": "20 cm LIDAR analysis"
  },
  {
    "fr": "Analyse du terrain",
    "en": "Terrain analysis"
  },
  {
    "fr": "Analyse des pentes",
    "en": "Slope analysis"
  },
  {
    "fr": "Analyse de l’altitude",
    "en": "Altitude analysis"
  },
  {
    "fr": "Météo et ensoleillement",
    "en": "Weather and sunlight"
  },
  {
    "fr": "Simulation ensoleillement",
    "en": "Sunlight simulation"
  },
  {
    "fr": "Prévisions et tendances Météo",
    "en": "Weather forecasts and trends"
  },
  {
    "fr": "Vent en temps réel",
    "en": "Real-time wind"
  },
  {
    "fr": "Simulation de la neige en temps réel",
    "en": "Real-time snow simulation"
  },
  {
    "fr": "Création d’itinéraire avancée",
    "en": "Advanced route planning"
  },
  {
    "fr": "Création d’itinéraire customisable",
    "en": "Customizable route creation"
  },
  {
    "fr": "Comparaison d’itinéraire",
    "en": "Route comparison"
  },
  {
    "fr": "Analyse d’itinéraire",
    "en": "Route analysis"
  },
  {
    "fr": "Graphique customisable",
    "en": "Customizable chart"
  },
  {
    "fr": "Feuille de route et timeline exportables",
    "en": "Exportable roadbook and timeline"
  },
  {
    "fr": "Export multi format",
    "en": "Multi-format export"
  },
  {
    "fr": "Gestion des Points d’Intérêts",
    "en": "POI management"
  },
  {
    "fr": "Sélection et édition des POIs",
    "en": "POI selection and editing"
  },
  {
    "fr": "Estimation du rythme",
    "en": "Pace estimation"
  },
  {
    "fr": "Pacing et gestion des pauses",
    "en": "Pacing and pause management"
  },
  {
    "fr": "Votre mode de paiement :",
    "en": "Your payment method:"
  },
  {
    "fr": "Votre compte démarre sur le plan Demo. Ouvrez RedView Web depuis cet onglet pour passer à une offre payante quand vous le souhaitez.",
    "en": "Your account starts on the Demo plan. Open RedView Web from this tab to switch to a paid plan whenever you want."
  },
  {
    "fr": "Votre abonnement RedView Pro est actif.",
    "en": "Your RedView Pro subscription is active."
  },
  {
    "fr": "Public",
    "en": "Public"
  },
  {
    "fr": "Privé",
    "en": "Private"
  },
  {
    "fr": "Sans nom",
    "en": "Untitled"
  },
  {
    "fr": "copie",
    "en": "copy"
  },
  {
    "fr": "Projet introuvable.",
    "en": "Project not found."
  },
  {
    "fr": "Session expirée. Reconnectez-vous pour gérer votre abonnement.",
    "en": "Session expired. Sign back in to manage your subscription."
  },
  {
    "fr": "La requête de facturation a échoué.",
    "en": "The billing request failed."
  },
  {
    "fr": "Session utilisateur introuvable.",
    "en": "User session not found."
  },
  {
    "fr": "Impossible de charger les projets.",
    "en": "Unable to load projects."
  },
  {
    "fr": "Échec de la création du projet.",
    "en": "Failed to create the project."
  },
  {
    "fr": "Échec de la création du dossier.",
    "en": "Failed to create the folder."
  },
  {
    "fr": "Échec du renommage.",
    "en": "Rename failed."
  },
  {
    "fr": "Échec de la suppression.",
    "en": "Delete failed."
  },
  {
    "fr": "Échec du renommage du dossier.",
    "en": "Folder rename failed."
  },
  {
    "fr": "Échec de la suppression du dossier.",
    "en": "Folder deletion failed."
  },
  {
    "fr": "Projet déplacé dans le dossier.",
    "en": "Project moved to the folder."
  },
  {
    "fr": "Projet déplacé à la racine.",
    "en": "Project moved to the root."
  },
  {
    "fr": "Impossible de déplacer ce projet.",
    "en": "Unable to move this project."
  },
  {
    "fr": "Dossier déplacé.",
    "en": "Folder moved."
  },
  {
    "fr": "Dossier déplacé à la racine.",
    "en": "Folder moved to the root."
  },
  {
    "fr": "Impossible de déplacer ce dossier.",
    "en": "Unable to move this folder."
  },
  {
    "fr": "Impossible de dupliquer ce projet.",
    "en": "Unable to duplicate this project."
  },
  {
    "fr": "Dernière connexion indisponible",
    "en": "Last connection unavailable"
  },
  {
    "fr": "Projet dupliqué: {{name}}",
    "en": "Project duplicated: {{name}}"
  },
  {
    "fr": "Dernière connexion le {{date}} à {{time}}",
    "en": "Last connection on {{date}} at {{time}}"
  },
  {
    "fr": "{{brand}} se terminant par {{last4}}",
    "en": "{{brand}} ending in {{last4}}"
  },
  {
    "fr": "Expire {{date}}.",
    "en": "Expires {{date}}."
  },
  {
    "fr": "Votre abonnement se terminera le {{date}}.",
    "en": "Your subscription will end on {{date}}."
  },
  {
    "fr": "Votre abonnement se renouvelle automatiquement le {{date}}.",
    "en": "Your subscription renews automatically on {{date}}."
  },
  {
    "fr": "Supprimer définitivement « {{name}} » ?",
    "en": "Permanently delete “{{name}}”?"
  },
  {
    "fr": "Supprimer définitivement le dossier « {{name}} » ? Il doit être vide avant suppression.",
    "en": "Permanently delete the folder “{{name}}”? It must be empty before deletion."
  },
  {
    "fr": "Ouvrir {{name}}",
    "en": "Open {{name}}"
  },
  {
    "fr": "Entrer dans {{name}}",
    "en": "Enter {{name}}"
  },
  {
    "fr": "Ouvrir le dossier {{name}}",
    "en": "Open folder {{name}}"
  },
  {
    "fr": "Entrer dans le dossier {{name}}",
    "en": "Enter folder {{name}}"
  },
  {
    "fr": "Fonds de carte",
    "en": "Basemaps"
  },
  {
    "fr": "Standard (clair)",
    "en": "Standard (light)"
  },
  {
    "fr": "Standard (sombre)",
    "en": "Standard (dark)"
  },
  {
    "fr": "Satellite",
    "en": "Satellite"
  },
  {
    "fr": "Qualité 3D",
    "en": "3D quality"
  },
  {
    "fr": "0.40 m (Lent)",
    "en": "0.40 m (Slow)"
  },
  {
    "fr": "30 m (Rapide)",
    "en": "30 m (Fast)"
  },
  {
    "fr": "Étiquettes",
    "en": "Labels"
  },
  {
    "fr": "POI Labels",
    "en": "POI Labels"
  },
  {
    "fr": "Villes",
    "en": "Cities"
  },
  {
    "fr": "États / Régions",
    "en": "States / Regions"
  },
  {
    "fr": "Parcs Naturels",
    "en": "Natural Parks"
  },
  {
    "fr": "Pays",
    "en": "Countries"
  },
  {
    "fr": "Plans d’eau",
    "en": "Water bodies"
  },
  {
    "fr": "Plans d'eau",
    "en": "Water bodies"
  },
  {
    "fr": "Courbes de niveau",
    "en": "Contour lines"
  },
  {
    "fr": "Disponible uniquement avec le fond Topographique.",
    "en": "Available only with the Topographic basemap."
  },
  {
    "fr": "Opacité",
    "en": "Opacity"
  },
  {
    "fr": "Activer {{title}}",
    "en": "Enable {{title}}"
  },
  {
    "fr": "Réduire",
    "en": "Collapse"
  },
  {
    "fr": "Développer",
    "en": "Expand"
  },
  {
    "fr": "Topographique",
    "en": "Topographic"
  },
  {
    "fr": "Itinéraires",
    "en": "Routes"
  },
  {
    "fr": "Défaut",
    "en": "Default"
  },
  {
    "fr": "Pente",
    "en": "Slope"
  },
  {
    "fr": "Vitesse est.",
    "en": "Est. speed"
  },
  {
    "fr": "Masquer la trace",
    "en": "Hide route"
  },
  {
    "fr": "Afficher la trace",
    "en": "Show route"
  },
  {
    "fr": "Cliquer pour éditer l’opacité",
    "en": "Click to edit opacity"
  },
  {
    "fr": "Choisir la couleur de {{name}}",
    "en": "Choose color for {{name}}"
  },
  {
    "fr": "Épaisseur des tracés",
    "en": "Route width"
  },
  {
    "fr": "Pentes",
    "en": "Slopes"
  },
  {
    "fr": "Résolution",
    "en": "Resolution"
  },
  {
    "fr": "Type de colorisation",
    "en": "Colorization type"
  },
  {
    "fr": "Échelle",
    "en": "Scale"
  },
  {
    "fr": "Réglage échelle",
    "en": "Scale setting"
  },
  {
    "fr": "Dégradé",
    "en": "Gradient"
  },
  {
    "fr": "Remplissage",
    "en": "Fill"
  },
  {
    "fr": "Pourcentage",
    "en": "Percentage"
  },
  {
    "fr": "8 couleurs",
    "en": "8 colors"
  },
  {
    "fr": "10 couleurs",
    "en": "10 colors"
  },
  {
    "fr": "Masquer la bande",
    "en": "Hide band"
  },
  {
    "fr": "Afficher la bande",
    "en": "Show band"
  },
  {
    "fr": "Cliquer pour modifier le pourcentage",
    "en": "Click to edit percentage"
  },
  {
    "fr": "Cliquer pour modifier l'angle",
    "en": "Click to edit angle"
  },
  {
    "fr": "Pourcentage de pente",
    "en": "Slope percentage"
  },
  {
    "fr": "Angle en degrés",
    "en": "Angle in degrees"
  },
  {
    "fr": "Altitude",
    "en": "Altitude"
  },
  {
    "fr": "2 couleurs",
    "en": "2 colors"
  },
  {
    "fr": "3 couleurs",
    "en": "3 colors"
  },
  {
    "fr": "4 couleurs",
    "en": "4 colors"
  },
  {
    "fr": "6 couleurs",
    "en": "6 colors"
  },
  {
    "fr": "Cliquer pour modifier l'altitude",
    "en": "Click to edit altitude"
  },
  {
    "fr": "Altitude en mètres",
    "en": "Altitude in meters"
  },
  {
    "fr": "Masquer le niveau",
    "en": "Hide level"
  },
  {
    "fr": "Afficher le niveau",
    "en": "Show level"
  },
  {
    "fr": "Choisir la couleur du niveau {{name}}",
    "en": "Choose color for level {{name}}"
  },
  {
    "fr": "Météo",
    "en": "Weather"
  },
  {
    "fr": "Ensoleillement",
    "en": "Sunlight"
  },
  {
    "fr": "Vent",
    "en": "Wind"
  },
  {
    "fr": "Forecast (+4j)",
    "en": "Forecast (+4d)"
  },
  {
    "fr": "Tendances",
    "en": "Trends"
  },
  {
    "fr": "Aujourd'hui",
    "en": "Today"
  },
  {
    "fr": "Particules",
    "en": "Particles"
  },
  {
    "fr": "Overlay terrain",
    "en": "Terrain overlay"
  },
  {
    "fr": "Sélectionner la date du vent",
    "en": "Select wind date"
  },
  {
    "fr": "Sélectionner l'heure du vent",
    "en": "Select wind time"
  },
  {
    "fr": "Valeur {{unit}}",
    "en": "Value {{unit}}"
  },
  {
    "fr": "Cliquer pour modifier la valeur {{unit}}",
    "en": "Click to edit value {{unit}}"
  },
  {
    "fr": "Masquer la bande météo",
    "en": "Hide weather band"
  },
  {
    "fr": "Afficher la bande météo",
    "en": "Show weather band"
  },
  {
    "fr": "Ajouter des alertes",
    "en": "Add alerts"
  },
  {
    "fr": "Choisir une date personnalisée",
    "en": "Choose a custom date"
  },
  {
    "fr": "Opacité ombres",
    "en": "Shadow opacity"
  },
  {
    "fr": "Opacité carte d'ensoleillement",
    "en": "Sunlight map opacity"
  },
  {
    "fr": "Opacité des ombres",
    "en": "Shadow opacity"
  },
  {
    "fr": "Lever",
    "en": "Sunrise"
  },
  {
    "fr": "Coucher",
    "en": "Sunset"
  },
  {
    "fr": "Afficher la carte d'ensoleillement",
    "en": "Show sunlight map"
  },
  {
    "fr": "Réduire la carte d'ensoleillement",
    "en": "Collapse sunlight map"
  },
  {
    "fr": "Développer la carte d'ensoleillement",
    "en": "Expand sunlight map"
  },
  {
    "fr": "Afficher la trajectoire",
    "en": "Show trajectory"
  },
  {
    "fr": "Tuiles LIDAR ( {{count}} )",
    "en": "LIDAR tiles ( {{count}} )"
  },
  {
    "fr": "Téléchargement {{progress}}",
    "en": "Downloading {{progress}}"
  },
  {
    "fr": "Téléchargement en cours",
    "en": "Download in progress"
  },
  {
    "fr": "Télécharger une tuile LIDAR",
    "en": "Download a LIDAR tile"
  },
  {
    "fr": "Clique sur la carte pour choisir une tuile",
    "en": "Click on the map to choose a tile"
  },
  {
    "fr": "Mode sélection actif",
    "en": "Selection mode active"
  },
  {
    "fr": "Active le mode puis clique sur la carte",
    "en": "Enable the mode, then click on the map"
  },
  {
    "fr": "Cliquer pour renommer",
    "en": "Click to rename"
  },
  {
    "fr": "Ouvrir dans le viewer 3D",
    "en": "Open in 3D viewer"
  },
  {
    "fr": "Ouvrir dans le viewer 3D LIDAR",
    "en": "Open in LIDAR 3D viewer"
  },
  {
    "fr": "Supprimer la tuile",
    "en": "Delete tile"
  },
  {
    "fr": "Tuile {{index}} (LIDAR) ({{size}}mo) ({{year}} IGN)",
    "en": "Tile {{index}} (LIDAR) ({{size}} MB) ({{year}} IGN)"
  },
  {
    "fr": "Routes",
    "en": "Roads"
  },
  {
    "fr": "Villes & Lieux",
    "en": "Cities & places"
  },
  {
    "fr": "Parcs Naturels",
    "en": "Natural parks"
  },
  {
    "fr": "Frontières",
    "en": "Borders"
  },
  {
    "fr": "Plans d\\'eau",
    "en": "Water bodies"
  },
  {
    "fr": "Tout masquer",
    "en": "Hide all"
  },
  {
    "fr": "Tout afficher",
    "en": "Show all"
  },
  {
    "fr": "Départ",
    "en": "Start"
  },
  {
    "fr": "Destination",
    "en": "Destination"
  },
  {
    "fr": "Date de départ",
    "en": "Start date"
  },
  {
    "fr": "Heure de départ",
    "en": "Start time"
  },
  {
    "fr": "Départ :",
    "en": "Start:"
  },
  {
    "fr": "Heure :",
    "en": "Time:"
  },
  {
    "fr": "Homme",
    "en": "Male"
  },
  {
    "fr": "Femme",
    "en": "Female"
  },
  {
    "fr": "Activités passées",
    "en": "Past activities"
  },
  {
    "fr": "Uploader un fichier .fit",
    "en": "Upload a .fit file"
  },
  {
    "fr": "Upload .fit",
    "en": "Upload .fit"
  },
  {
    "fr": "FTP",
    "en": "FTP"
  },
  {
    "fr": "FTP :",
    "en": "FTP:"
  },
  {
    "fr": "Poids système",
    "en": "System weight"
  },
  {
    "fr": "Poids système :",
    "en": "System weight:"
  },
  {
    "fr": "Pneus",
    "en": "Tires"
  },
  {
    "fr": "Pneus :",
    "en": "Tires:"
  },
  {
    "fr": "Surfaces",
    "en": "Surfaces"
  },
  {
    "fr": "Poids météo",
    "en": "Weather weight"
  },
  {
    "fr": "Poids surfaces",
    "en": "Surface weight"
  },
  {
    "fr": "Sexe :",
    "en": "Gender:"
  },
  {
    "fr": "Sexe pour la prédiction",
    "en": "Gender for prediction"
  },
  {
    "fr": "Ajouter des pauses à chaque POI favori",
    "en": "Add pauses at each favorite POI"
  },
  {
    "fr": "Ajouter des pauses par interval",
    "en": "Add pauses by interval"
  },
  {
    "fr": "Ajouter une pause",
    "en": "Add a pause"
  },
  {
    "fr": "Calculer",
    "en": "Calculate"
  },
  {
    "fr": "Appliquer",
    "en": "Apply"
  },
  {
    "fr": "Charger",
    "en": "Load"
  },
  {
    "fr": "Priorités",
    "en": "Priorities"
  },
  {
    "fr": "Durée",
    "en": "Duration"
  },
  {
    "fr": "Dénivelé",
    "en": "Elevation gain"
  },
  {
    "fr": "Tranquilité",
    "en": "Calmness"
  },
  {
    "fr": "Types de route",
    "en": "Road types"
  },
  {
    "fr": "Singletrack",
    "en": "Singletrack"
  },
  {
    "fr": "Hors-piste",
    "en": "Off-road"
  },
  {
    "fr": "Voies cyclables",
    "en": "Bike lanes"
  },
  {
    "fr": "Voix cyclables",
    "en": "Bike lanes"
  },
  {
    "fr": "Axes majeurs",
    "en": "Main roads"
  },
  {
    "fr": "Ferry",
    "en": "Ferry"
  },
  {
    "fr": "Virages",
    "en": "Turns"
  },
  {
    "fr": "Pentes max.",
    "en": "Max slope"
  },
  {
    "fr": "Villes",
    "en": "Cities"
  },
  {
    "fr": "Appliquer à tout les itinéraires",
    "en": "Apply to all routes"
  },
  {
    "fr": "Prioriser",
    "en": "Prefer"
  },
  {
    "fr": "Tolérer",
    "en": "Tolerate"
  },
  {
    "fr": "Éviter",
    "en": "Avoid"
  },
  {
    "fr": "Interdire",
    "en": "Forbid"
  },
  {
    "fr": "Ajouter un élément",
    "en": "Add an item"
  },
  {
    "fr": "Choisir le type d'élément",
    "en": "Choose item type"
  },
  {
    "fr": "Étape",
    "en": "Step"
  },
  {
    "fr": "Contrôles de la vue carte",
    "en": "Map view controls"
  },
  {
    "fr": "Activer ou quitter le mode plein écran",
    "en": "Enter or exit fullscreen mode"
  },
  {
    "fr": "Plein écran",
    "en": "Fullscreen"
  },
  {
    "fr": "Recentrer la boussole vers le nord",
    "en": "Recenter the compass to north"
  },
  {
    "fr": "Nord",
    "en": "North"
  },
  {
    "fr": "Zoomer",
    "en": "Zoom in"
  },
  {
    "fr": "Dézoomer",
    "en": "Zoom out"
  },
  {
    "fr": "Passer en vue 2D",
    "en": "Switch to 2D view"
  },
  {
    "fr": "Passer en vue 3D",
    "en": "Switch to 3D view"
  },
  {
    "fr": "Passer en 2D",
    "en": "Switch to 2D"
  },
  {
    "fr": "Passer en 3D",
    "en": "Switch to 3D"
  },
  {
    "fr": "Zone d’analyse",
    "en": "Analysis zone"
  },
  {
    "fr": "Tracer une zone d’analyse",
    "en": "Draw an analysis zone"
  },
  {
    "fr": "Zone d’analyse terrain (pentes, altitude, ensoleillement)",
    "en": "Terrain analysis zone (slopes, altitude, sunlight)"
  },
  {
    "fr": "Redessiner la zone",
    "en": "Redraw the zone"
  },
  {
    "fr": "Zoomer sur la zone",
    "en": "Zoom to the zone"
  },
  {
    "fr": "Supprimer la zone",
    "en": "Delete the zone"
  },
  {
    "fr": "Cliquez pour placer les sommets, double-cliquez pour terminer, Échap pour annuler",
    "en": "Click to place vertices, double-click to finish, Esc to cancel"
  },
  {
    "fr": "1 sommet placé — cliquez pour le 2e",
    "en": "1 vertex placed — click for the 2nd"
  },
  {
    "fr": "2 sommets placés — cliquez pour le 3e",
    "en": "2 vertices placed — click for the 3rd"
  },
  {
    "fr": "Double-cliquez ou cliquez sur le 1er point pour valider",
    "en": "Double-click or click the 1st point to validate"
  },
  {
    "fr": "Valider",
    "en": "Validate"
  },
  {
    "fr": "Annuler point",
    "en": "Undo point"
  },
  {
    "fr": "Annuler",
    "en": "Cancel"
  },
  {
    "fr": "Zone très étendue — les calculs resteront plus lents qu’avec une zone réduite",
    "en": "Very large zone — computations will stay slower than with a smaller zone"
  },
  {
    "fr": "Zone d’analyse requise — tracez-la pour activer",
    "en": "Analysis zone required — draw one to enable"
  },
  {
    "fr": "Zone d’analyse active",
    "en": "Analysis zone active"
  },
  {
    "fr": "Menu contextuel de la carte",
    "en": "Map context menu"
  },
  {
    "fr": "Nouveau POI",
    "en": "New POI"
  },
  {
    "fr": "Coordonnées",
    "en": "Coordinates"
  },
  {
    "fr": "Altitude",
    "en": "Altitude"
  },
  {
    "fr": "Pente :",
    "en": "Slope:"
  },
  {
    "fr": "Revêtement :",
    "en": "Surface:"
  },
  {
    "fr": "Type :",
    "en": "Type:"
  },
  {
    "fr": "Sélectionner",
    "en": "Select"
  },
  {
    "fr": "Ouvrir Street View",
    "en": "Open Street View"
  },
  {
    "fr": "Copier les coordonnées",
    "en": "Copy coordinates"
  },
  {
    "fr": "Créer un POI",
    "en": "Create a POI"
  },
  {
    "fr": "Démarrer ici",
    "en": "Start here"
  },
  {
    "fr": "Ajouter une étape",
    "en": "Add a waypoint"
  },
  {
    "fr": "Finir ici",
    "en": "Finish here"
  },
  {
    "fr": "Nouveau projet",
    "en": "New project"
  },
  {
    "fr": "Nom du projet",
    "en": "Project name"
  },
  {
    "fr": "Projet non enregistré",
    "en": "Unsaved project"
  },
  {
    "fr": "Non enregistré",
    "en": "Unsaved"
  },
  {
    "fr": "Retour au gestionnaire en cours",
    "en": "Returning to project browser"
  },
  {
    "fr": "Retour au gestionnaire de projet",
    "en": "Back to project browser"
  },
  {
    "fr": "Paramètres du projet",
    "en": "Project settings"
  },
  {
    "fr": "Télécharger",
    "en": "Download"
  },
  {
    "fr": "Partager",
    "en": "Share"
  },
  {
    "fr": "Traçage",
    "en": "Routing"
  },
  {
    "fr": "Mode d'édition",
    "en": "Edit mode"
  },
  {
    "fr": "Panneau d’itinéraire",
    "en": "Itinerary panel"
  },
  {
    "fr": "Timeline en plein écran",
    "en": "Fullscreen timeline"
  },
  {
    "fr": "Redimensionner le panneau",
    "en": "Resize panel"
  },
  {
    "fr": "Itinéraires",
    "en": "Routes"
  },
  {
    "fr": "Renommer {{name}}",
    "en": "Rename {{name}}"
  },
  {
    "fr": "Cliquer à nouveau pour renommer",
    "en": "Click again to rename"
  },
  {
    "fr": "Itinéraire chargé depuis un GPX",
    "en": "Route imported from a GPX file"
  },
  {
    "fr": "Supprimer {{name}}",
    "en": "Delete {{name}}"
  },
  {
    "fr": "Nouvel itinéraire",
    "en": "New route"
  },
  {
    "fr": "Gravel (défaut)",
    "en": "Gravel (default)"
  },
  {
    "fr": "Gravel",
    "en": "Gravel"
  },
  {
    "fr": "Route",
    "en": "Road"
  },
  {
    "fr": "VTT",
    "en": "MTB"
  },
  {
    "fr": "Touring",
    "en": "Touring"
  },
  {
    "fr": "Personnalisé",
    "en": "Custom"
  },
  {
    "fr": "Rechercher un lieu",
    "en": "Search for a place"
  },
  {
    "fr": "Itinéraire {{index}}",
    "en": "Route {{index}}"
  },
  {
    "fr": "Variante 2",
    "en": "Variant 2"
  },
  {
    "fr": "Synthèse d'itinéraire",
    "en": "Route summary"
  },
  {
    "fr": "Synthèse",
    "en": "Summary"
  },
  {
    "fr": "Aucun itinéraire",
    "en": "No route"
  },
  {
    "fr": "Plus d'options",
    "en": "More options"
  },
  {
    "fr": "{{name}} commence à {{distance}} km",
    "en": "{{name}} starts at {{distance}} km"
  },
  {
    "fr": "Replier les traces filles",
    "en": "Collapse child traces"
  },
  {
    "fr": "Déplier les traces filles",
    "en": "Expand child traces"
  },
  {
    "fr": "Masquer le graphique",
    "en": "Hide chart"
  },
  {
    "fr": "Afficher le graphique",
    "en": "Show chart"
  },
  {
    "fr": "Nouveau nom pour {{name}}",
    "en": "New name for {{name}}"
  },
  {
    "fr": "{{name}} · Double-cliquez pour renommer",
    "en": "{{name}} · Double-click to rename"
  },
  {
    "fr": "Plus d'options pour {{name}}",
    "en": "More options for {{name}}"
  },
  {
    "fr": "Actions pour {{name}}",
    "en": "Actions for {{name}}"
  },
  {
    "fr": "Renommer la trace",
    "en": "Rename route"
  },
  {
    "fr": "Dupliquer la trace",
    "en": "Duplicate route"
  },
  {
    "fr": "Supprimer la trace",
    "en": "Delete route"
  },
  {
    "fr": "Analyse du parcours",
    "en": "Route analysis"
  },
  {
    "fr": "Analyse",
    "en": "Analysis"
  },
  {
    "fr": "Mode d'analyse",
    "en": "Analysis mode"
  },
  {
    "fr": "Distance",
    "en": "Distance"
  },
  {
    "fr": "Temps",
    "en": "Time"
  },
  {
    "fr": "Heures",
    "en": "Hours"
  },
  {
    "fr": "Détail",
    "en": "Detail"
  },
  {
    "fr": "Zoom du graphique",
    "en": "Chart zoom"
  },
  {
    "fr": "Dézoomer le graphique",
    "en": "Zoom out chart"
  },
  {
    "fr": "Zoomer le graphique",
    "en": "Zoom in chart"
  },
  {
    "fr": "Axe 1",
    "en": "Axis 1"
  },
  {
    "fr": "Axe 2",
    "en": "Axis 2"
  },
  {
    "fr": "Filtres",
    "en": "Filters"
  },
  {
    "fr": "Graphique d'analyse",
    "en": "Analysis chart"
  },
  {
    "fr": "Renseigne une date et une heure de départ pour activer Jour/nuit.",
    "en": "Set a departure date and time to enable Day/Night."
  },
  {
    "fr": "Waypoint",
    "en": "Waypoint"
  },
  {
    "fr": "Pause",
    "en": "Pause"
  },
  {
    "fr": "Alertes",
    "en": "Alerts"
  },
  {
    "fr": "Profil d'altitude",
    "en": "Altitude profile"
  },
  {
    "fr": "Jour/nuit",
    "en": "Day/Night"
  },
  {
    "fr": "Vitesse",
    "en": "Speed"
  },
  {
    "fr": "Vitesse moyenne",
    "en": "Average speed"
  },
  {
    "fr": "Puissance",
    "en": "Power"
  },
  {
    "fr": "Puissance moyenne",
    "en": "Average power"
  },
  {
    "fr": "Inclinaison (°)",
    "en": "Slope (deg)"
  },
  {
    "fr": "Inclinaison (%)",
    "en": "Slope (%)"
  },
  {
    "fr": "Surface",
    "en": "Surface"
  },
  {
    "fr": "Température",
    "en": "Temperature"
  },
  {
    "fr": "Température ressentie (°)",
    "en": "Feels like (deg)"
  },
  {
    "fr": "Pluie (mm)",
    "en": "Rain (mm)"
  },
  {
    "fr": "Vent (km/h)",
    "en": "Wind (km/h)"
  },
  {
    "fr": "Couverture nuageuse (%)",
    "en": "Cloud cover (%)"
  },
  {
    "fr": "Humidité (%)",
    "en": "Humidity (%)"
  },
  {
    "fr": "Ensoleillement (min)",
    "en": "Sunshine (min)"
  },
  {
    "fr": "Itinéraire(s)",
    "en": "Route(s)"
  },
  {
    "fr": "Feuille de route",
    "en": "Roadbook"
  },
  {
    "fr": "Timeline",
    "en": "Timeline"
  },
  {
    "fr": "Graphique",
    "en": "Chart"
  },
  {
    "fr": "Exporter",
    "en": "Export"
  },
  {
    "fr": "Panneau central d'analyse",
    "en": "Central analysis panel"
  },
  {
    "fr": "Déplacement horizontal du graphique",
    "en": "Horizontal chart movement"
  },
  {
    "fr": "Déplacer la zone visible du graphique",
    "en": "Move the visible chart area"
  },
  {
    "fr": "Modifier la durée de la pause",
    "en": "Edit pause duration"
  },
  {
    "fr": "Modifier la durée (min)",
    "en": "Edit duration (min)"
  },
  {
    "fr": "Modifier la distance (km)",
    "en": "Edit distance (km)"
  },
  {
    "fr": "Modifier la distance en kilomètres",
    "en": "Edit distance in kilometers"
  },
  {
    "fr": "Masquer",
    "en": "Hide"
  },
  {
    "fr": "Afficher",
    "en": "Show"
  },
  {
    "fr": "Favori verrouille par pause automatique",
    "en": "Favorite locked by automatic pause"
  },
  {
    "fr": "Favori",
    "en": "Favorite"
  },
  {
    "fr": "Supprimer",
    "en": "Delete"
  },
  {
    "fr": "Trace supprimée",
    "en": "Route deleted"
  },
  {
    "fr": "Nouvel itinéraire créé",
    "en": "New route created"
  },
  {
    "fr": "Réduction possible: {{count}} point en moins",
    "en": "Possible reduction: {{count}} fewer point"
  },
  {
    "fr": "Réduction possible: {{count}} points en moins",
    "en": "Possible reduction: {{count}} fewer points"
  },
  {
    "fr": "Trace déjà assez légère",
    "en": "Route is already light enough"
  },
  {
    "fr": "{{count}} passage trop raide détecté",
    "en": "{{count}} section too steep detected"
  },
  {
    "fr": "{{count}} passages trop raides détectés",
    "en": "{{count}} sections too steep detected"
  },
  {
    "fr": "Aucun passage trop raide détecté",
    "en": "No section too steep detected"
  },
  {
    "fr": "Nettoyage de trace disponible",
    "en": "Route cleanup available"
  },
  {
    "fr": "Trace réduite à {{value}} pts/km",
    "en": "Route reduced to {{value}} pts/km"
  },
  {
    "fr": "Aucune aberration détectée",
    "en": "No anomalies detected"
  },
  {
    "fr": "Trace nettoyée",
    "en": "Route cleaned"
  },
  {
    "fr": "Sens du GPX inversé",
    "en": "GPX direction reversed"
  },
  {
    "fr": "Inversion indisponible pour cette trace",
    "en": "Reverse is unavailable for this route"
  },
  {
    "fr": "Audit indisponible pour cette trace",
    "en": "Audit is unavailable for this route"
  },
  {
    "fr": "Aucune galère détectée",
    "en": "No issues detected"
  },
  {
    "fr": "{{count}} portion à vérifier",
    "en": "{{count}} section to review"
  },
  {
    "fr": "{{count}} portions à vérifier",
    "en": "{{count}} sections to review"
  },
  {
    "fr": "Audit masqué",
    "en": "Audit hidden"
  },
  {
    "fr": "Barre d\\'outils centrale",
    "en": "Central toolbar"
  },
  {
    "fr": "Outils d'édition du parcours",
    "en": "Route editing tools"
  },
  {
    "fr": "Lecture du parcours",
    "en": "Route playback"
  },
  {
    "fr": "Ralentir le flyover",
    "en": "Slow down flyover"
  },
  {
    "fr": "Mettre en pause le flyover",
    "en": "Pause flyover"
  },
  {
    "fr": "Lancer le flyover",
    "en": "Start flyover"
  },
  {
    "fr": "Accélérer le flyover",
    "en": "Speed up flyover"
  },
  {
    "fr": "Revenir au début du flyover",
    "en": "Return to start of flyover"
  },
  {
    "fr": "Résumé de lecture",
    "en": "Playback summary"
  },
  {
    "fr": "Réduction de points GPX",
    "en": "GPX point reduction"
  },
  {
    "fr": "Simplification intelligente",
    "en": "Smart simplification"
  },
  {
    "fr": "Paramètre GPX",
    "en": "GPX parameter"
  },
  {
    "fr": "Points source",
    "en": "Source points"
  },
  {
    "fr": "Points rendus",
    "en": "Rendered points"
  },
  {
    "fr": "Cible expert",
    "en": "Expert target"
  },
  {
    "fr": "Ouvrir expert GPX",
    "en": "Open GPX expert"
  },
  {
    "fr": "Fermer expert GPX",
    "en": "Close GPX expert"
  },
  {
    "fr": "Mode Expert GPX",
    "en": "GPX expert mode"
  },
  {
    "fr": "Préserver le profil tout en réduisant le nombre de points affichés.",
    "en": "Preserve route shape while reducing the number of rendered points."
  },
  {
    "fr": "Appliquer expert GPX",
    "en": "Apply GPX expert"
  },
  {
    "fr": "Detaillé courant: {{value}} pts/km",
    "en": "Current detail: {{value}} pts/km"
  },
  {
    "fr": "Repères utiles: détaillé 40-80 pts/km, léger 15-30 pts/km",
    "en": "Useful markers: detailed 40-80 pts/km, light 15-30 pts/km"
  },
  {
    "fr": "Densité cible",
    "en": "Target density"
  },
  {
    "fr": "Distance indisponible",
    "en": "Distance unavailable"
  },
  {
    "fr": "Nouveau point",
    "en": "New point"
  },
  {
    "fr": "Point d\\'intérêt",
    "en": "Point Of Interest"
  },
  {
    "fr": "Catégories POI",
    "en": "POI categories"
  },
  {
    "fr": "Eau",
    "en": "Water"
  },
  {
    "fr": "Toilette",
    "en": "Toilet"
  },
  {
    "fr": "Station Service",
    "en": "Fuel station"
  },
  {
    "fr": "Magasin de vélo",
    "en": "Bike shop"
  },
  {
    "fr": "Erreur de recherche",
    "en": "Search error"
  },
  {
    "fr": "Eau",
    "en": "Water"
  },
  {
    "fr": "Toilettes",
    "en": "Toilets"
  },
  {
    "fr": "Supermarché",
    "en": "Supermarket"
  },
  {
    "fr": "Carburant",
    "en": "Fuel"
  },
  {
    "fr": "Boulangerie",
    "en": "Bakery"
  },
  {
    "fr": "Fast-food",
    "en": "Fast food"
  },
  {
    "fr": "Café",
    "en": "Cafe"
  },
  {
    "fr": "Bar",
    "en": "Bar"
  },
  {
    "fr": "Restaurant",
    "en": "Restaurant"
  },
  {
    "fr": "Vélo",
    "en": "Bike"
  },
  {
    "fr": "Hôtel",
    "en": "Hotel"
  },
  {
    "fr": "Refuge",
    "en": "Refuge"
  },
  {
    "fr": "Col",
    "en": "Pass"
  },
  {
    "fr": "Activez au moins un export avant de lancer le téléchargement.",
    "en": "Enable at least one export before starting the download."
  },
  {
    "fr": "Aucun itinéraire actif à exporter.",
    "en": "No active route to export."
  },
  {
    "fr": "Le format sélectionné n'est pas encore pris en charge pour l'itinéraire.",
    "en": "The selected format is not yet supported for the route."
  },
  {
    "fr": "La feuille de route est uniquement disponible en export Excel.",
    "en": "The roadbook is only available as an Excel export."
  },
  {
    "fr": "{{files}} exporté depuis l'itinéraire actif.",
    "en": "{{files}} exported from the active route."
  },
  {
    "fr": "{{files}} exportés depuis l'itinéraire actif.",
    "en": "{{files}} exported from the active route."
  },
  {
    "fr": "Impossible d'exporter l'itinéraire actif.",
    "en": "Unable to export the active route."
  },
  {
    "fr": "Panneau d'export",
    "en": "Export panel"
  },
  {
    "fr": "Réduire le module exporter",
    "en": "Collapse export module"
  },
  {
    "fr": "Développer le module exporter",
    "en": "Expand export module"
  },
  {
    "fr": "Export...",
    "en": "Exporting..."
  },
  {
    "fr": "Veuillez sélectionner un fichier .gpx",
    "en": "Please select a .gpx file"
  },
  {
    "fr": "Impossible de lire ce GPX",
    "en": "Unable to read this GPX"
  },
  {
    "fr": "Créer un itinéraire",
    "en": "Create a route"
  },
  {
    "fr": "Créer un nouvel itinéraire",
    "en": "Create a new route"
  },
  {
    "fr": "Dupliquer à partir de l’itinéraire sélectionné",
    "en": "Duplicate from the selected route"
  },
  {
    "fr": "Lecture du GPX…",
    "en": "Reading GPX…"
  },
  {
    "fr": "Uploader un fichier gpx",
    "en": "Upload a GPX file"
  },
  {
    "fr": "Sélection de date",
    "en": "Date selection"
  },
  {
    "fr": "Mois précédent",
    "en": "Previous month"
  },
  {
    "fr": "Mois suivant",
    "en": "Next month"
  },
  {
    "fr": "Aujourd'hui",
    "en": "Today"
  },
  {
    "fr": "Vue de la feuille de route",
    "en": "Roadbook view"
  },
  {
    "fr": "Paramètres de la feuille de route",
    "en": "Roadbook settings"
  },
  {
    "fr": "Choisir le type d'élément à ajouter",
    "en": "Choose the item type to add"
  },
  {
    "fr": "Quitter le plein écran",
    "en": "Exit fullscreen"
  },
  {
    "fr": "Ouvrir en plein écran",
    "en": "Open fullscreen"
  },
  {
    "fr": "Paramètres de la timeline",
    "en": "Timeline settings"
  },
  {
    "fr": "Échelle",
    "en": "Scale"
  },
  {
    "fr": "Échelle de la timeline",
    "en": "Timeline scale"
  },
  {
    "fr": "Date",
    "en": "Date"
  },
  {
    "fr": "Repère",
    "en": "Marker"
  },
  {
    "fr": "Repère kilométrique",
    "en": "Distance marker"
  },
  {
    "fr": "Zoom de la timeline",
    "en": "Timeline zoom"
  },
  {
    "fr": "Réduire le zoom",
    "en": "Zoom out"
  },
  {
    "fr": "Augmenter le zoom",
    "en": "Zoom in"
  },
  {
    "fr": "Zoom",
    "en": "Zoom"
  },
  {
    "fr": "Filtres de la timeline",
    "en": "Timeline filters"
  },
  {
    "fr": "Filtres de la feuille de route",
    "en": "Roadbook filters"
  },
  {
    "fr": "Favoris",
    "en": "Favorites"
  },
  {
    "fr": "POIs sur carte",
    "en": "POIs on map"
  },
  {
    "fr": "POIs sur itinéraires",
    "en": "POIs on routes"
  },
  {
    "fr": "Pauses",
    "en": "Pauses"
  },
  {
    "fr": "Points de passage",
    "en": "Waypoints"
  },
  {
    "fr": "Liste des étapes",
    "en": "Steps list"
  },
  {
    "fr": "Type",
    "en": "Type"
  },
  {
    "fr": "Recherche…",
    "en": "Searching…"
  },
  {
    "fr": "Aucun résultat",
    "en": "No results"
  },
  {
    "fr": "Fontaines",
    "en": "Fountains"
  },
  {
    "fr": "Supermarchés",
    "en": "Supermarkets"
  },
  {
    "fr": "Station Service",
    "en": "Gas station"
  },
  {
    "fr": "Magasin de vélo",
    "en": "Bike shop"
  },
  {
    "fr": "Hôtels",
    "en": "Hotels"
  },
  {
    "fr": "Refuges",
    "en": "Refuges"
  },
  {
    "fr": "Durée de pause — {{label}}",
    "en": "Pause duration — {{label}}"
  },
  {
    "fr": "Durée de {{label}}",
    "en": "Duration of {{label}}"
  },
  {
    "fr": "Interval",
    "en": "Interval"
  },
  {
    "fr": "Interval de {{label}}",
    "en": "Interval of {{label}}"
  },
  {
    "fr": "Supprimer {{label}}",
    "en": "Delete {{label}}"
  },
  {
    "fr": "{{axis1}} et {{axis2}} ne sont pas encore disponibles.",
    "en": "{{axis1}} and {{axis2}} are not available yet."
  },
  {
    "fr": "Aucune prédiction calculée — lancez « Calculer ».",
    "en": "No prediction has been computed yet — click \"Calculate\"."
  },
  {
    "fr": "{{count}} POI regroupés. Cliquer pour zoomer sur cette zone.",
    "en": "{{count}} clustered POIs. Click to zoom into this area."
  },
  {
    "fr": "{{duration}} · cliquer pour modifier",
    "en": "{{duration}} · click to edit"
  },
  {
    "fr": "Cliquez sur la carte pour placer le départ",
    "en": "Click on the map to place the start"
  },
  {
    "fr": "Cliquez sur la carte pour placer l’arrivée",
    "en": "Click on the map to place the finish"
  },
  {
    "fr": "Cliquez sur la carte pour prolonger le tracé",
    "en": "Click on the map to extend the route"
  },
  {
    "fr": "Départ ajouté. Cliquez pour placer l’arrivée",
    "en": "Start added. Click to place the finish"
  },
  {
    "fr": "Arrivée ajoutée. Cliquez pour prolonger le tracé",
    "en": "Finish added. Click to extend the route"
  },
  {
    "fr": "Point ajouté, recalcul du tracé en cours",
    "en": "Point added, route recalculation in progress"
  },
  {
    "fr": "Trace découpée: {{name}}",
    "en": "Route split: {{name}}"
  },
  {
    "fr": "Cliquez sur la trace pour la découper",
    "en": "Click on the route to split it"
  },
  {
    "fr": "Fusion impossible: trace introuvable.",
    "en": "Merge failed: route not found."
  },
  {
    "fr": "Fusion impossible: il faut deux traces calculées.",
    "en": "Merge failed: two computed routes are required."
  },
  {
    "fr": "Fusion impossible: trace source ou cible invalide.",
    "en": "Merge failed: invalid source or target route."
  },
  {
    "fr": "Fusion en cours...",
    "en": "Merging..."
  },
  {
    "fr": "Fusion impossible: extrémités de trace invalides.",
    "en": "Merge failed: invalid route endpoints."
  },
  {
    "fr": "Le raccord de fusion sort de la zone autorisée.",
    "en": "The merge connector leaves the allowed area."
  },
  {
    "fr": "Fusion impossible avec les traces sélectionnées.",
    "en": "Merge failed with the selected routes."
  },
  {
    "fr": "Fusion créée avec raccord BRouter simplifié entre les deux traces.",
    "en": "Merge created with a simplified BRouter connector between the two routes."
  },
  {
    "fr": "Fusion créée avec raccord BRouter allégé entre les deux traces.",
    "en": "Merge created with a lighter BRouter connector between the two routes."
  },
  {
    "fr": "Fusion créée avec raccord BRouter entre les deux traces.",
    "en": "Merge created with a BRouter connector between the two routes."
  },
  {
    "fr": "Fusion créée.",
    "en": "Merge created."
  },
  {
    "fr": "Erreur pendant la fusion.",
    "en": "Error while merging."
  },
  {
    "fr": "Trace source sélectionnée. Choisissez la trace à ajouter.",
    "en": "Source route selected. Choose the route to add."
  },
  {
    "fr": "Sélectionnez le tracé source puis le tracé à fusionner.",
    "en": "Select the source route, then the route to merge."
  },
  {
    "fr": "Zone interdite: clic droit pour placer le premier sommet",
    "en": "Forbidden area: right-click to place the first vertex"
  },
  {
    "fr": "Polygone prêt: clic droit pour ajouter un sommet, éditez les poignées puis recliquez sur Interdire pour enregistrer",
    "en": "Polygon ready: right-click to add a vertex, edit the handles, then click Forbid again to save"
  },
  {
    "fr": "Impossible d’enregistrer la zone interdite",
    "en": "Unable to save the forbidden area"
  },
  {
    "fr": "Zone interdite enregistrée",
    "en": "Forbidden area saved"
  },
  {
    "fr": "Tableau",
    "en": "Table"
  },
  {
    "fr": "Distance entre waypoints (km)",
    "en": "Distance between waypoints (km)"
  },
  {
    "fr": "Jours de la timeline",
    "en": "Timeline days"
  },
  {
    "fr": "Timeline journaliere",
    "en": "Daily timeline"
  },
  {
    "fr": "Annuler",
    "en": "Undo"
  },
  {
    "fr": "Rétablir",
    "en": "Redo"
  },
  {
    "fr": "Enregistrer le profil",
    "en": "Save profile"
  },
  {
    "fr": "Bientôt disponible.",
    "en": "Coming soon."
  },
  {
    "fr": "Points d'intérêt",
    "en": "Points of interest"
  },
  {
    "fr": "Redimensionner la feuille de route",
    "en": "Resize the roadbook"
  },
  {
    "fr": "Distance {{label}}",
    "en": "{{label}} distance"
  },
  {
    "fr": "Affiner les résultats (beta)",
    "en": "Refine results (beta)"
  },
  {
    "fr": "Catégories",
    "en": "Categories"
  },
  {
    "fr": "Recherche… {{pct}}%",
    "en": "Searching… {{pct}}%"
  },
  {
    "fr": "Recharger ({{count}})",
    "en": "Reload ({{count}})"
  },
  {
    "fr": "Rechercher",
    "en": "Search"
  },
  {
    "fr": "({{count}} POI trouvés)",
    "en": "({{count}} POIs found)"
  },
  {
    "fr": "Profil de routage",
    "en": "Routing profile"
  },
  {
    "fr": "Itinéraire",
    "en": "Itinerary"
  },
  {
    "fr": "Calcul du tracé en cours",
    "en": "Route calculation in progress"
  },
  {
    "fr": "Importez un fichier GPX pour rechercher les POI le long du parcours.",
    "en": "Import a GPX file to search for POIs along the route."
  },
  {
    "fr": "Activez au moins une catégorie ci-dessus.",
    "en": "Enable at least one category above."
  },
  {
    "fr": "Impossible de recharger les fichiers FIT du projet.",
    "en": "Unable to reload the project FIT files."
  },
  {
    "fr": "Aucun fichier FIT valide sélectionné.",
    "en": "No valid FIT file selected."
  },
  {
    "fr": "Projet Supabase introuvable pour sauvegarder les FIT.",
    "en": "Supabase project not found to save FIT files."
  },
  {
    "fr": "Impossible de sauvegarder les fichiers FIT dans le bucket du projet.",
    "en": "Unable to save FIT files in the project bucket."
  },
  {
    "fr": "Chargez au moins un fichier FIT avant de calculer.",
    "en": "Upload at least one FIT file before calculating."
  },
  {
    "fr": "L’itinéraire actif n’a pas encore de trace GPX exploitable.",
    "en": "The active route does not yet have a usable GPX track."
  },
  {
    "fr": "Le profil altimetrique du trace BRouter n\\'est pas encore pret. Relancez le calcul quand le trace est charge.",
    "en": "The elevation profile of the BRouter track is not ready yet. Retry once the track has loaded."
  },
  {
    "fr": "Le GPX actif ne contient pas assez d\\'altitudes exploitables pour la prediction.",
    "en": "The active GPX does not contain enough usable elevation data for prediction."
  },
  {
    "fr": "Le moteur de prediction FIT n’est pas prêt.",
    "en": "The FIT prediction engine is not ready."
  },
  {
    "fr": "Erreur inconnue pendant la prediction FIT.",
    "en": "Unknown error during FIT prediction."
  },
  {
    "fr": "Mode Expert — profil BRouter sur-mesure",
    "en": "Expert mode — custom BRouter profile"
  },
  {
    "fr": "Ajustez chaque paramètre du moteur de routage. Tout reste local à votre navigateur ; les changements s’appliquent au prochain calcul d’itinéraire.",
    "en": "Adjust every routing-engine parameter. Everything stays local in your browser; changes apply to the next route calculation."
  },
  {
    "fr": "Fermer",
    "en": "Close"
  },
  {
    "fr": "Activer Mode Expert",
    "en": "Enable expert mode"
  },
  {
    "fr": "{{count}} modif",
    "en": "{{count}} change"
  },
  {
    "fr": "{{count}} modifs",
    "en": "{{count}} changes"
  },
  {
    "fr": "Masquer BRF",
    "en": "Hide BRF"
  },
  {
    "fr": "Voir BRF",
    "en": "View BRF"
  },
  {
    "fr": "Astuce : tout est calculé côté client. Vos profils ne quittent jamais votre navigateur, sauf si vous cliquez sur « Téléverser » (à venir) pour les utiliser sur d’autres appareils.",
    "en": "Tip: everything is computed client-side. Your profiles never leave your browser, unless you click \"Upload\" (coming soon) to use them on other devices."
  },
  {
    "fr": "avancé",
    "en": "advanced"
  },
  {
    "fr": "Réinitialiser {{label}}",
    "en": "Reset {{label}}"
  },
  {
    "fr": "Profil BRF généré",
    "en": "Generated BRF profile"
  },
  {
    "fr": "Copié ✓",
    "en": "Copied ✓"
  },
  {
    "fr": "Copier",
    "en": "Copy"
  },
  {
    "fr": "Compatible avec",
    "en": "Compatible with"
  },
  {
    "fr": "pour des tests avancés. Ce code est généré localement, dans votre navigateur uniquement.",
    "en": "for advanced tests. This code is generated locally, in your browser only."
  },
  {
    "fr": "Itinéraire hors zone autorisée.",
    "en": "Route outside the allowed area."
  },
  {
    "fr": "Erreur BRouter",
    "en": "BRouter error"
  },
  {
    "fr": "Impossible de calculer l’itinéraire : le point d’arrivée se trouve dans une zone interdite.",
    "en": "Unable to calculate route: destination point is in a forbidden zone."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : le point de départ se trouve dans une zone interdite.",
    "en": "Unable to calculate route: start point is in a forbidden zone."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : un point de passage se trouve dans une zone interdite.",
    "en": "Unable to calculate route: a waypoint is in a forbidden zone."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : un point se trouve dans une zone interdite.",
    "en": "Unable to calculate route: a point is in a forbidden zone."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : le point de départ est hors de la zone couverte ou inaccessible.",
    "en": "Unable to calculate route: start point is outside the covered area or inaccessible."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : le point d’arrivée est hors de la zone couverte ou inaccessible.",
    "en": "Unable to calculate route: destination point is outside the covered area or inaccessible."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : un point est hors de la zone couverte ou inaccessible.",
    "en": "Unable to calculate route: a point is outside the covered area or inaccessible."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : aucun tracé praticable trouvé entre ces points.",
    "en": "Unable to calculate route: no viable path found between these points."
  },
  {
    "fr": "Le calcul de l’itinéraire a pris trop de temps. Déplacez vos points ou simplifiez le tracé.",
    "en": "Route calculation timed out. Move your points or simplify the route."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : les points doivent être situés en France métropolitaine ou en Corse.",
    "en": "Unable to calculate route: points must be located in mainland France or Corsica."
  },
  {
    "fr": "Le serveur de calcul d’itinéraire est temporairement inaccessible. Veuillez réessayer.",
    "en": "Route calculation server is temporarily unreachable. Please try again."
  },
  {
    "fr": "Erreur dans le profil de traçage personnalisé. Vérifiez vos paramètres.",
    "en": "Error in custom routing profile. Check your settings."
  },
  {
    "fr": "Impossible de calculer l’itinéraire : vérifiez l’emplacement de vos points et des zones interdites.",
    "en": "Unable to calculate route: check the placement of your points and forbidden zones."
  },
  {
    "fr": "Impossible de calculer l’itinéraire pour ces points.",
    "en": "Unable to calculate route for these points."
  },
  {
    "fr": "Impossible de calculer l’itinéraire.",
    "en": "Unable to calculate route."
  },
  {
    "fr": "Supprimer la zone interdite",
    "en": "Delete forbidden zone"
  }
];
