export const MIN_USABLE_SAMPLE_FILL_RATIO = 0.70;
export const PARTIAL_SAMPLE_RETRY_DELAY_MS = 1200;
export const MAX_PARTIAL_SAMPLE_RETRIES = 4;
export const MIN_VISIBLE_SHADOW_ALPHA_RATIO = 0.001;
export const STYLE_PREPARATION_RETRY_DELAY_MS = 250;
