/**
 * A single timeline item card — used in both Sheet and Timeline views.
 *
 * Layout (reading left → right, all driven by flexbox auto-layout):
 *   [✓] [KindBadge] [Kind label]  [Name (flex)]  [Distance]  [Actions]
 *
 * Actions are three utility buttons: visibility toggle (eye), favorite
 * (star), delete (trash). Their state is controlled by the parent via
 * callbacks, never inferred locally — so the component stays stateless and
 * ready to wire to any backend.
 */
import { IconEye, IconStar, IconTrash } from '../../components/icons';
import { useAppI18n } from '@/shared/i18n';
import { PlaceSearchInput } from './components';
import type { TimelineItem } from '../../types';
import { KindBadge, kindLabel } from './KindBadge';

interface TimelineRowProps {
  item: TimelineItem;
  /** When true, the row is rendered in "compact" mode (Timeline rail). */
  compact?: boolean;
  /** Optional inline style — used by the Timeline view to absolutely-position. */
  style?: React.CSSProperties;
  selected?: boolean;
  onToggleSelect?: (id: string, selected: boolean) => void;
  onToggleVisibility?: (id: string, visible: boolean) => void;
  onToggleFavorite?: (id: string, favorite: boolean) => void;
  onRemove?: (id: string) => void;
  /** When provided, start/end placeholder rows render an inline place search. */
  onSelectPlace?: (
    id: string,
    place: { name: string; fullName: string; lat: number; lon: number },
  ) => void;
}

function formatDistance(km: number | null): string {
  if (km === null) return '—';
  if (km === 0) return '0';
  if (km < 1) return `${Math.round(km * 1000)} m`;
  return km.toFixed(1);
}

function resolveTimelineRowKindLabel(item: TimelineItem, t: (key: string) => string): string {
  if (item.kind === 'end') return t('Fin');
  return kindLabel(item.kind, item.poiCategory);
}

export function TimelineRow({
  item,
  compact = false,
  style,
  selected = false,
  onToggleSelect,
  onToggleVisibility,
  onToggleFavorite,
  onRemove,
  onSelectPlace,
}: TimelineRowProps) {
  const { t } = useAppI18n();
  const searchPlaceholder = t('Rechercher un lieu');
  const isPlaceholder =
    item.label === searchPlaceholder || item.label === 'Rechercher un lieu' || item.label.trim() === '';
  const visible = item.visible !== false;
  const isAutoGeneratedIntervalPause = item.autoGenerated === 'intervalPause';
  const isLocationRow =
    item.kind === 'start' || item.kind === 'end' || item.kind === 'waypoint';
  const useSearchInput = !!onSelectPlace && isLocationRow;
  const rowKindLabel = resolveTimelineRowKindLabel(item, t);

  // For "pause" items, the primary label is the duration.
  const primaryLabel =
    item.kind === 'pause' && item.durationMin
      ? (isAutoGeneratedIntervalPause ? `${item.label} · ${item.durationMin}min` : `${item.durationMin}min`)
      : item.label;

  return (
    <div
      className={`rvi-tl-row${isPlaceholder ? ' rvi-tl-row--placeholder' : ''}${
        compact ? ' rvi-tl-row--compact' : ''
      }${selected ? ' is-selected' : ''}`}
      style={style}
      data-kind={item.kind}
    >
      <label className="rvi-tl-row__check" aria-label={t('Sélectionner')}>
        <input
          type="checkbox"
          checked={selected}
          onChange={(e) => onToggleSelect?.(item.id, e.target.checked)}
        />
        <span className="rvi-tl-row__check-box" aria-hidden />
      </label>

      <KindBadge kind={item.kind} poiCategory={item.poiCategory} size={24} />

      <span className="rvi-tl-row__kind-text" title={rowKindLabel}>
        {rowKindLabel}
      </span>

      {useSearchInput ? (
        <PlaceSearchInput
          value={isPlaceholder ? '' : item.label}
          onPick={(s) =>
            onSelectPlace?.(item.id, {
              name: s.name,
              fullName: s.fullName,
              lat: s.lat,
              lon: s.lon,
            })
          }
          placeholder={searchPlaceholder}
        />
      ) : (
        <span
          className={`rvi-tl-row__title${
            isPlaceholder ? ' rvi-tl-row__title--placeholder' : ''
          }`}
          title={primaryLabel}
        >
          {primaryLabel}
        </span>
      )}

      <span className="rvi-tl-row__distance">{formatDistance(item.distanceKm)}</span>

      <span className="rvi-tl-row__actions">
        <button
          type="button"
          className={`rvi-tl-row__action${visible ? ' is-on' : ''}`}
          onClick={() => {
            if (isAutoGeneratedIntervalPause) return;
            onToggleVisibility?.(item.id, !visible);
          }}
          aria-label={visible ? t('Masquer') : t('Afficher')}
          aria-pressed={visible}
          disabled={isAutoGeneratedIntervalPause}
        >
          <IconEye size={15} />
        </button>
        <button
          type="button"
          className="rvi-tl-row__action rvi-tl-row__action--danger"
          onClick={() => {
            if (isAutoGeneratedIntervalPause) return;
            onRemove?.(item.id);
          }}
          aria-label={t('Supprimer')}
          disabled={isAutoGeneratedIntervalPause}
        >
          <IconTrash size={15} />
        </button>
        <button
          type="button"
          className={`rvi-tl-row__action rvi-tl-row__action--star${item.favorite ? ' is-on is-fav' : ''}`}
          onClick={() => {
            if (isAutoGeneratedIntervalPause) return;
            onToggleFavorite?.(item.id, !item.favorite);
          }}
          aria-label={t('Favori')}
          aria-pressed={!!item.favorite}
          disabled={isAutoGeneratedIntervalPause}
        >
          <IconStar size={12} />
        </button>
      </span>
    </div>
  );
}
