/**
 * Full catalog of BRouter parameters exposed in Expert Mode.
 *
 * Sources:
 *   - `misc/profiles2/trekking.brf` (every `assign foo = bar # %foo% | desc | type`)
 *   - `docs/developers/profile_developers_guide.md`
 *
 * Each entry maps 1-to-1 with a `profile:<id>` URL override that the
 * BRouter standalone server understands without requiring a custom
 * profile upload — the trekking profile defines all of these as
 * `assign` in its `---context:global` section.
 *
 * If you add a parameter here, double-check it appears as `assign` in
 * the chosen base profile (see `panelProfileToBrouter` in
 * `lib/brouter/profiles/profile-overrides.ts`); otherwise the override is
 * silently ignored by BRouter.
 */
import type { ParameterDefinition } from './types';

const TURN_INSTR_MODES = [
  { value: 0, label: '0 — Aucune' },
  { value: 1, label: '1 — Auto' },
  { value: 2, label: '2 — Locus' },
  { value: 3, label: '3 — OsmAnd' },
  { value: 4, label: '4 — Commentaires' },
  { value: 5, label: '5 — GPSies' },
  { value: 6, label: '6 — Orux' },
  { value: 7, label: '7 — Locus (ancien)' },
];

export const ALL_PARAMETERS: ParameterDefinition[] = [
  /* ───────────────────────── Comportement ──────────────────────── */
  {
    id: 'allow_steps',
    label: 'Autoriser les escaliers',
    hint: 'Inclut les `highway=steps`. Désactiver pour un vélo de route.',
    group: 'comportement',
    kind: 'boolean',
    default: true,
  },
  {
    id: 'allow_ferries',
    label: 'Autoriser les ferries',
    hint: 'Désactivé = jamais de traversée maritime.',
    group: 'comportement',
    kind: 'boolean',
    default: true,
  },
  {
    id: 'ignore_cycleroutes',
    label: 'Ignorer les véloroutes',
    hint:
      'Désactive les bonus accordés aux itinéraires cyclables balisés ' +
      '(souvent au profit du dénivelé).',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'stick_to_cycleroutes',
    label: 'Coller aux véloroutes',
    hint: 'N’emprunte que des véloroutes balisées dès que possible.',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'use_proposed_cycleroutes',
    label: 'Inclure les véloroutes proposées',
    hint: 'Considère les itinéraires `proposed` au même niveau que les officiels.',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'avoid_unsafe',
    label: 'Éviter les routes dangereuses',
    hint:
      'Pénalise fortement les routes principales sans piste cyclable ' +
      'attenante.',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'consider_noise',
    label: 'Privilégier le calme (bruit)',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'consider_river',
    label: 'Privilégier les bords de cours d’eau',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'consider_forest',
    label: 'Privilégier forêts et parcs',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'consider_town',
    label: 'Contourner les agglomérations',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'consider_traffic',
    label: 'Éviter le trafic estimé',
    group: 'comportement',
    kind: 'boolean',
    default: false,
  },
  {
    id: 'add_beeline',
    label: 'Beeline si point isolé',
    hint:
      'Ajoute un segment en ligne droite quand le point de départ ou ' +
      'd’arrivée est loin du réseau routier.',
    group: 'comportement',
    kind: 'boolean',
    default: false,
    advanced: true,
  },

  /* ─────────────────────────── Dénivelé ────────────────────────── */
  {
    id: 'consider_elevation',
    label: 'Tenir compte du dénivelé',
    hint: 'Si désactivé, le profil ignore complètement les montées/descentes.',
    group: 'elevation',
    kind: 'boolean',
    default: true,
  },
  {
    id: 'uphillcost',
    label: 'Coût en montée',
    hint: 'Multiplicateur de coût pour 1 m d’ascension. Plus élevé = plus évité.',
    group: 'elevation',
    kind: 'number',
    default: 0,
    min: 0,
    max: 200,
    step: 5,
  },
  {
    id: 'uphillcutoff',
    label: 'Seuil ignoré (montée)',
    hint: 'Pentes inférieures à ce % sont ignorées dans le calcul.',
    group: 'elevation',
    kind: 'number',
    default: 1.5,
    min: 0,
    max: 10,
    step: 0.1,
    unit: '%',
  },
  {
    id: 'downhillcost',
    label: 'Coût en descente',
    group: 'elevation',
    kind: 'number',
    default: 60,
    min: 0,
    max: 300,
    step: 5,
  },
  {
    id: 'downhillcutoff',
    label: 'Seuil ignoré (descente)',
    group: 'elevation',
    kind: 'number',
    default: 1.5,
    min: 0,
    max: 10,
    step: 0.1,
    unit: '%',
  },
  {
    id: 'uphillmaxslope',
    label: 'Pente max. en montée',
    hint:
      'Au-delà de ce %, le coût en montée passe à `uphillmaxslopecost`. ' +
      'Sert à interdire les murs.',
    group: 'elevation',
    kind: 'number',
    default: 12,
    min: 1,
    max: 50,
    step: 1,
    unit: '%',
    advanced: true,
  },
  {
    id: 'uphillmaxslopecost',
    label: 'Coût au-dessus de la pente max.',
    group: 'elevation',
    kind: 'number',
    default: 500,
    min: 0,
    max: 5000,
    step: 50,
    advanced: true,
  },
  {
    id: 'downhillmaxslope',
    label: 'Pente max. en descente',
    group: 'elevation',
    kind: 'number',
    default: 12,
    min: 1,
    max: 50,
    step: 1,
    unit: '%',
    advanced: true,
  },
  {
    id: 'downhillmaxslopecost',
    label: 'Coût au-dessus de la pente max. (descente)',
    group: 'elevation',
    kind: 'number',
    default: 500,
    min: 0,
    max: 5000,
    step: 50,
    advanced: true,
  },
  {
    id: 'elevationpenaltybuffer',
    label: 'Tampon de pénalité (m)',
    hint: 'Volume d’élévation absorbé sans appliquer le coût de montée/descente.',
    group: 'elevation',
    kind: 'number',
    default: 5,
    min: 0,
    max: 100,
    step: 1,
    unit: 'm',
    advanced: true,
  },
  {
    id: 'elevationmaxbuffer',
    label: 'Tampon max. (m)',
    group: 'elevation',
    kind: 'number',
    default: 10,
    min: 1,
    max: 200,
    step: 1,
    unit: 'm',
    advanced: true,
  },
  {
    id: 'elevationbufferreduce',
    label: 'Réduction tampon (%/km)',
    group: 'elevation',
    kind: 'number',
    default: 0,
    min: 0,
    max: 5,
    step: 0.1,
    advanced: true,
  },

  /* ────────────────────── Cinématique (temps) ──────────────────── */
  {
    id: 'totalMass',
    label: 'Masse totale (vélo + cycliste)',
    group: 'cinematique',
    kind: 'number',
    default: 90,
    min: 30,
    max: 200,
    step: 1,
    unit: 'kg',
  },
  {
    id: 'maxSpeed',
    label: 'Vitesse max.',
    group: 'cinematique',
    kind: 'number',
    default: 45,
    min: 10,
    max: 100,
    step: 1,
    unit: 'km/h',
  },
  {
    id: 'S_C_x',
    label: 'Cx · Surface frontale',
    hint: 'Coefficient de traînée × aire de référence (m²).',
    group: 'cinematique',
    kind: 'number',
    default: 0.225,
    min: 0.05,
    max: 1,
    step: 0.005,
    advanced: true,
  },
  {
    id: 'C_r',
    label: 'Coefficient de roulement',
    group: 'cinematique',
    kind: 'number',
    default: 0.01,
    min: 0.001,
    max: 0.05,
    step: 0.001,
    advanced: true,
  },
  {
    id: 'bikerPower',
    label: 'Puissance moyenne',
    group: 'cinematique',
    kind: 'number',
    default: 100,
    min: 30,
    max: 500,
    step: 5,
    unit: 'W',
  },

  /* ────────────────── Instructions de navigation ──────────────── */
  {
    id: 'turnInstructionMode',
    label: 'Mode',
    group: 'instructions',
    kind: 'enum',
    default: 1,
    choices: TURN_INSTR_MODES,
  },
  {
    id: 'turnInstructionCatchingRange',
    label: 'Distance de regroupement (m)',
    group: 'instructions',
    kind: 'number',
    default: 40,
    min: 5,
    max: 200,
    step: 5,
    unit: 'm',
  },
  {
    id: 'turnInstructionRoundabouts',
    label: 'Hints spécifiques aux ronds-points',
    group: 'instructions',
    kind: 'boolean',
    default: true,
  },
  {
    id: 'considerTurnRestrictions',
    label: 'Respecter les restrictions de virage',
    group: 'instructions',
    kind: 'boolean',
    default: true,
    advanced: true,
  },

  /* ────────────────────── Moteur de routage ───────────────────── */
  {
    id: 'correctMisplacedViaPoints',
    label: 'Corriger les via-points mal placés',
    group: 'moteur',
    kind: 'boolean',
    default: false,
    advanced: true,
  },
  {
    id: 'correctMisplacedViaPointsDistance',
    label: 'Distance max. de correction (m)',
    group: 'moteur',
    kind: 'number',
    default: 400,
    min: 0,
    max: 5000,
    step: 50,
    unit: 'm',
    advanced: true,
  },
  {
    id: 'continueStraight',
    label: 'Continuer tout droit après via',
    group: 'moteur',
    kind: 'boolean',
    default: false,
    advanced: true,
  },
  {
    id: 'use_dynamic_range',
    label: 'Plage dynamique de raccrochage',
    hint: 'Étend la recherche du point de départ jusqu’à ~50 km si nécessaire.',
    group: 'moteur',
    kind: 'boolean',
    default: true,
    advanced: true,
  },
  {
    id: 'check_start_way',
    label: 'Vérifier la qualité du point de départ',
    group: 'moteur',
    kind: 'boolean',
    default: false,
    advanced: true,
  },
  {
    id: 'pass1coefficient',
    label: 'Coefficient passe 1',
    hint: 'Heuristique de la première passe. < 0 désactive la passe.',
    group: 'moteur',
    kind: 'number',
    default: 1.5,
    min: -1,
    max: 5,
    step: 0.1,
    advanced: true,
  },
  {
    id: 'pass2coefficient',
    label: 'Coefficient passe 2',
    group: 'moteur',
    kind: 'number',
    default: 0,
    min: -1,
    max: 5,
    step: 0.1,
    advanced: true,
  },
  {
    id: 'processUnusedTags',
    label: 'Lister tous les tags OSM',
    hint: 'Debug : affiche tous les tags présents même s’ils ne sont pas utilisés.',
    group: 'moteur',
    kind: 'boolean',
    default: false,
    advanced: true,
  },
];

export function getParameter(id: string): ParameterDefinition | undefined {
  return ALL_PARAMETERS.find((p) => p.id === id);
}
